export const languages=['zh','en','fr'];
export const email='tangy38722@163.com';
export const categories=[
 {id:'science',cover:'science',films:[],name:['科普类','Science explainers','Vulgarisation scientifique'],desc:['用清晰的动画与可视化讲解，把科学原理与技术流程讲明白。','Clear animation and visual explanations make scientific ideas and technical processes easier to understand.','Des animations et des explications visuelles pour rendre les principes scientifiques et les procédés techniques accessibles.'],tags:[['科学原理','能源技术','知识可视化'],['Scientific concepts','Energy technology','Visual explanations'],['Principes scientifiques','Technologies énergétiques','Explications visuelles']]},
 {id:'brand',cover:3,films:[3,17,21,22,45,49,51,52,56,57,59],name:['品牌广告','Brand & advertising','Marques & publicité'],desc:['用创意、叙事与视觉风格，建立鲜明的品牌表达。','Distinctive brand expression through ideas, storytelling and visual craft.','Une expression de marque singulière, portée par les idées, le récit et l’image.'],tags:[['TVC 广告','品牌态度片','汽车创意短片'],['TVC commercials','Brand films','Automotive storytelling'],['Spots publicitaires','Films de marque','Récits automobiles']]},
 {id:'product',cover:58,films:[4,5,6,40,43,47,58],name:['电商与产品','Products & commerce','Produits & e-commerce'],desc:['从产品形象到跨境种草，让功能、质感与使用场景被看见。','From product films to cross-border commerce, reveal features, materials and everyday use.','Du film produit aux contenus e-commerce internationaux, révéler les usages, les matières et les atouts.'],tags:[['产品形象','跨境电商','场景种草'],['Product imagery','Cross-border commerce','Lifestyle content'],['Image produit','E-commerce international','Contenus lifestyle']]},
 {id:'corporate',cover:16,films:[15,16,27,28,29,30],name:['政企与公共传播','Corporate & public communication','Entreprises & communication publique'],desc:['把机构信息与公共议题，转化为清晰、有温度的影像内容。','Turn institutional messages and public-interest topics into clear, human stories.','Donner une forme claire et humaine aux messages institutionnels et aux sujets d’intérêt général.'],tags:[['企业宣传','廉洁与反诈','公共安全'],['Corporate communication','Integrity & fraud prevention','Public safety'],['Communication institutionnelle','Intégrité & prévention des fraudes','Sécurité publique']]},
 {id:'events',cover:19,films:[14,18,19,24],name:['活动与赛事','Events & sport','Événements & sport'],desc:['从预热、倒计时到现场混剪，为每个关键时刻设计节奏。','Build momentum around key moments, from teasers and countdowns to event edits.','Créer le rythme des moments clés, du teasing au compte à rebours et au montage événementiel.'],tags:[['活动预热','开幕影像','赛事混剪'],['Event teasers','Opening films','Sports edits'],['Teasers événementiels','Films d’ouverture','Montages sportifs']]},
 {id:'overseas',cover:2,films:[1,2,7,8,9,10],name:['海外短剧','International short drama','Fictions courtes internationales'],desc:['面向海外观看场景，探索不同题材与语言的短剧表达。','Short-form storytelling across genres and languages for international audiences.','Explorer les genres et les langues dans des fictions courtes destinées aux publics internationaux.'],tags:[['英语短剧','葡语短剧','海外叙事'],['English-language drama','Portuguese-language drama','International storytelling'],['Fictions en anglais','Fictions en portugais','Récits internationaux']]},
 {id:'animation',cover:41,films:[25,31,32,39,41,44],name:['AI 叙事与动漫','AI stories & animation','Récits IA & animation'],desc:['让人物、世界观与镜头语言一起生长，延展想象的边界。','Bring characters, worlds and cinematic language together to expand what stories can show.','Faire grandir ensemble les personnages, les univers et le langage visuel pour élargir l’imaginaire.'],tags:[['AI 叙事短片','动漫与片头','创意世界观'],['AI narrative films','Animation & opening sequences','Imaginative worlds'],['Courts récits IA','Animation & génériques','Univers créatifs']]},
 {id:'cinema',cover:33,films:[12,13,20,26,33,34,35,46,48,50,54],name:['定制微电影','Bespoke short films','Courts métrages sur mesure'],desc:['把人生片段、情感与记忆，创作成有个人温度的电影。','Turn personal moments, emotions and memories into films with a human touch.','Transformer les moments de vie, les émotions et les souvenirs en films profondément personnels.'],tags:[['情感故事','纪念与婚礼','人生记录'],['Emotional storytelling','Celebrations & weddings','Life stories'],['Récits sensibles','Célébrations & mariages','Histoires de vie']]},
 {id:'places',cover:42,films:[42,53],name:['文旅与空间','Destinations & spaces','Destinations & lieux'],desc:['用影像传递一处目的地的氛围，呈现空间与体验的吸引力。','Capture the atmosphere of a destination and the appeal of its spaces and experiences.','Faire ressentir l’atmosphère d’une destination et l’attrait de ses lieux et expériences.'],tags:[['文旅宣传','酒店空间','目的地体验'],['Destination films','Hotels & spaces','Travel experiences'],['Films de destination','Hôtels & espaces','Expériences de voyage']]},
 {id:'avatar',cover:36,films:[36,37,38],name:['数字人口播','Digital presenters','Présentateurs numériques'],desc:['探索数字人出镜与信息讲述，为持续内容生产提供表达形式。','Explore digital presenters as a format for information-led, repeatable content.','Explorer les présentateurs numériques pour des contenus informatifs et réguliers.'],tags:[['数字人出镜','信息口播','内容生产'],['Digital avatars','Scripted presentation','Content production'],['Avatars numériques','Présentation scénarisée','Production de contenu']]}
];
const names=[
 ['BLOOD MOON OFFERING','BLOOD MOON OFFERING','BLOOD MOON OFFERING'],
 ['DAY ONE NOT DEAD','DAY ONE NOT DEAD','DAY ONE NOT DEAD'],
 ['Demora 家具 TVC','Demora Furniture TVC','Spot mobilier Demora'],
 ['Demora 家具跨境','Demora — Cross-border Commerce','Demora — Commerce international'],
 ['Demora 家具跨境口播','Demora — Product Presentation','Demora — Présentation produit'],
 ['Demora 家具跨境种草','Demora — Lifestyle Discovery','Demora — Découverte lifestyle'],
 ['SECRETS AFTER RTHE BALL','SECRETS AFTER RTHE BALL','SECRETS AFTER RTHE BALL'],
 ['SEGREDOS NO FUNERAL','SEGREDOS NO FUNERAL','SEGREDOS NO FUNERAL'],
 ['SUBJECT 007','SUBJECT 007','SUBJECT 007'],
 ['THE COFFIN BEARER','THE COFFIN BEARER','THE COFFIN BEARER'],
 ['三十岁，我们接着来','Thirty, and On We Go','Trente ans, et l’aventure continue'],
 ['三十岁 我们接着来','Thirty and On We Go','Trente ans et l’aventure continue'],
 ['三生三世微电影','Love Across Three Lifetimes','Un amour, trois vies'],
 ['中国人寿活动混剪','China Life — Event Edit','China Life — Montage événementiel'],
 ['中国人寿消防宣传','China Life — Fire Safety','China Life — Sécurité incendie'],
 ['清风护航 · 中开院廉洁 MV','Integrity in Motion — Music Video','L’intégrité en mouvement — Clip musical'],
 ['为热爱拍出锋芒 · 懂车帝','Driven by Passion — Dongchedi','Filmer sa passion — Dongchedi'],
 ['华发倒计时','Huafa — Countdown','Huafa — Compte à rebours'],
 ['华发开幕式','Huafa — Opening Ceremony','Huafa — Cérémonie d’ouverture'],
 ['后来我遇见了我','The Person I Became','La personne que je suis devenue'],
 ['向未知寻找答案','Answers Beyond the Familiar','Chercher les réponses dans l’inconnu'],
 ['听见内心的宁静','Listen to the Stillness Within','Écouter le calme intérieur'],
 ['国家网球中心剪辑','National Tennis Center — Event Edit','Centre national de tennis — Montage'],
 ['国家网球中心活动预热','National Tennis Center — Event Teaser','Centre national de tennis — Teaser'],
 ['夜色靠近时','When Night Draws Near','À l’approche de la nuit'],
 ['婚前微电影 · EN','Before the Wedding · EN','Avant le mariage · EN'],
 ['巴广渝高速廉洁宣传','Ba-Guang-Yu Expressway — Integrity Film','Autoroute Ba-Guang-Yu — Film sur l’intégrité'],
 ['广东连平农商银行 · 金融反诈','Lianping Rural Commercial Bank — Fraud Prevention','Banque rurale de Lianping — Prévention des fraudes'],
 ['广东连平农商银行 · 金融诈骗','Lianping Rural Commercial Bank — Financial Fraud','Banque rurale de Lianping — Fraudes financières'],
 ['中国电建廉洁 MV','POWERCHINA Integrity Music Video','POWERCHINA Clip musical sur l’intégrité'],
 ['微缩纪元 · 第一期：坠落','The Miniature Era · Episode 1: The Fall','L’Ère miniature · Épisode 1 : La chute'],
 ['心动的安全距离','A Safe Distance from Love','À bonne distance de l’amour'],
 ['我们的环球之旅','Our Journey Around the World','Notre voyage autour du monde'],
 ['把一生，留给童年','A Lifetime for Childhood','Toute une vie pour l’enfance'],
 ['折纸任意门','The Origami Door','La porte en origami'],
 ['数字人口播 01','Digital Presenter 01','Présentateur numérique 01'],
 ['数字人口播 02','Digital Presenter 02','Présentateur numérique 02'],
 ['数字人口播 03','Digital Presenter 03','Présentateur numérique 03'],
 ['旅途中的小小守护','Little Guardians Along the Way','De petites attentions en chemin'],
 ['日本捏捏电商视频','Squishy Toys — Japan E-commerce Film','Jouets sensoriels — E-commerce au Japon'],
 ['日漫 OP','Anime Opening Sequence','Générique d’animation japonaise'],
 ['星海岛宣传片','Xinghai Island — Destination Film','Île Xinghai — Film de destination'],
 ['智能陪护机器人','Intelligent Companion Robot','Robot d’accompagnement intelligent'],
 ['最后的真实心跳','The Last Real Heartbeat','Le dernier véritable battement'],
 ['模力 OPC 漫剧基地宣传','Moli OPC — AI Comics Production Hub','Moli OPC — Pôle de création de fictions IA'],
 ['此生有你','A Life with You','Une vie avec toi'],
 ['炎阳科技健康鞋产品宣传','Yanyang Technology — Health Footwear','Yanyang Technology — Chaussures bien-être'],
 ['爱情故事回忆录','A Memoir of Our Love','Les mémoires de notre amour'],
 ['男友被嫌穷 · 懂车帝','Judged by His Wallet — Dongchedi','Jugé sur son portefeuille — Dongchedi'],
 ['百变穿越','A Thousand Transformations','Mille métamorphoses'],
 ['让光，记住你','Let the Light Remember You','Que la lumière se souvienne de toi'],
 ['诸葛奇谋 · 懂车帝','Zhuge’s Strategy — Dongchedi','La stratégie de Zhuge — Dongchedi'],
 ['酒店宣传片','Hotel Brand Film','Film de présentation hôtelière'],
 ['阿呆，我会再找到你','Adai, I Will Find You Again','Adai, je te retrouverai'],
 ['雷羽觉醒','Thunderwing Awakens','L’éveil de l’aile du tonnerre'],
 ['领克品牌态度','Lynk & Co — Brand Manifesto','Lynk & Co — Manifeste de marque'],
 ['领克赛前预热','Lynk & Co — Race Teaser','Lynk & Co — Teaser de course'],
 ['高脚杯产品形象片','Stemware — Product Film','Verre à pied — Film produit']
];
export const removedFilmIds=[11,23,55];
names.push(['宝马 MINI 快剪','MINI Brand Edit','MINI Montage de marque']);
export const films=names.map((name,i)=>({id:i+1,name,category:categories.find(c=>c.films.includes(i+1))?.id})).filter(f=>!removedFilmIds.includes(f.id));
export const ui={
 nav:[['首页','作品','出海','培训','关于','联系'],['Home','Work','Global','Training','About','Contact'],['Accueil','Réalisations','International','Formations','À propos','Contact']],
 skip:['跳至正文','Skip to content','Aller au contenu'],menu:['菜单','Menu','Menu'],language:['切换语言','Change language','Changer de langue'],
 slogan:['让内容，<br>走得<span>更远</span>。','Take content<br><span>further.</span>','Donnons de<br>la portée à vos<br><span>contenus.</span>'],
 heroTag:['AI 科技 × 文化创意 × 内容表达','AI technology × Creativity × Storytelling','Technologie IA × Créativité × Narration'],
 heroDesc:['从创意到成片，从本土到世界。<br>以 AI 制作与专业协作，打开内容的更多可能。','From idea to screen. From local stories to the world.<br>AI production and expert collaboration bring possibilities to life.','De l’idée à l’écran. Des récits locaux au monde.<br>La production IA et la collaboration donnent vie aux possibles.'],
 explore:['探索作品','Explore our work','Explorer nos réalisations'],viewAll:['全部品类','All categories','Toutes les catégories'],learn:['了解更多','Learn more','En savoir plus'],
 homeSelected:['让想象，有迹可循。','Ideas, made visible.','Des idées qui prennent forme.'],
 homeSelectedDesc:['商业、叙事、情感。每一种表达，都有自己的语言。','Commercial, narrative, personal. Every story has its own language.','Commercial, narratif, personnel. Chaque récit a son langage.'],
 possibilities:['内容的每一站，都有我们。','A partner at every stage.','À chaque étape, un partenaire.'],
 servicesTitle:['从一个想法，到更大的可能。','From an idea to new possibilities.','D’une idée à de nouveaux possibles.'],
 contactCta:['下一段精彩，<br>从你的想法开始。','Your next story<br>starts with an idea.','Votre prochaine histoire<br>commence par une idée.'],
 write:['聊聊你的项目','Tell us about your project','Parlons de votre projet'],emailLabel:['合作邮箱','Business enquiries','Contact professionnel'],
 company:['深圳市元启程文化科技有限公司','AUROVOY Culture Technology Co., Ltd.','AUROVOY Culture Technology Co., Ltd.'],
 workTitle:['不止一种风格，<br>不止一种可能。','Many formats.<br>More possibilities.','Des formats variés.<br>Des possibilités multiples.'],
 workIntro:['从商业传播到原创叙事，让不同内容找到合适的表达。','From commercial communication to original storytelling, explore the many forms our work can take.','De la communication commerciale aux récits originaux, découvrez les différentes formes de nos créations.'],
 samples:['个样片版本','sample versions','versions de démonstration'],viewCat:['浏览品类','Explore category','Explorer la catégorie'],
 works:['样片作品','Sample films','Films de démonstration'],category:['作品品类','Category','Catégorie'],originalTitle:['原始片名','Original title','Titre original'],
 preview:['网页预览片段 · 最长 45 秒，保留样片原有语言。','Web preview · Up to 45 seconds, in the sample’s original language.','Extrait web · 45 secondes maximum, dans la langue d’origine du film.'],
 related:['继续探索同类作品','More in this category','À découvrir dans cette catégorie'],project:['有类似的制作需求？','Have a similar project in mind?','Un projet similaire en tête ?'],
 discuss:['沟通制作需求','Discuss your brief','Échanger sur votre projet'],backCat:['返回品类','Back to category','Retour à la catégorie'],
 production:['内容制作与交付','Content production','Production de contenu'],training:['实战培训与赋能','Training & enablement','Formation & accompagnement'],global:['内容出海启动','Global Start','Lancement à l’international'],
 productionDesc:['商业影像、AI 短剧、微电影与本地化制作。从目标梳理到质量验收，协同完成内容交付。','Commercial films, AI drama, bespoke cinema and localisation, coordinated from the initial brief to final review.','Films commerciaux, fictions IA, courts métrages et localisation : une production coordonnée du brief à la validation.'],
 trainingDesc:['公开课、7 天实战营与企业定制内训，用项目方法连接学习与真实作品。','Introductory sessions, seven-day workshops and tailored corporate training, linking learning with real work.','Sessions découverte, ateliers sur sept jours et formations d’entreprise, pour relier l’apprentissage à la création.'],
 globalDesc:['帮助内容团队梳理目标市场、本地化与启动路径，形成预算、排期和专业资源协同方案。','Help content teams plan markets, localisation, budgets, schedules and the expert resources needed to launch.','Aider les équipes à définir marchés, localisation, budgets, calendrier et ressources pour se lancer.'],
 processTitle:['好创意，需要好的交付。','Great ideas deserve great delivery.','Les bonnes idées méritent une réalisation soignée.'],
 process:[[['理解需求','明确目标、受众、预算与周期。'],['设计方案','确认脚本、视觉方向与制作范围。'],['协同制作','按项目匹配伙伴，分阶段推进。'],['验收交付','按约定完成内容与技术检查。']],[['Understand','Define objectives, audience, budget and timeline.'],['Design','Agree on the script, visual direction and scope.'],['Produce','Coordinate specialists and review work in stages.'],['Deliver','Complete the agreed creative and technical checks.']],[['Comprendre','Préciser objectifs, public, budget et calendrier.'],['Concevoir','Valider scénario, direction visuelle et périmètre.'],['Produire','Coordonner les spécialistes et les étapes.'],['Livrer','Effectuer les contrôles créatifs et techniques convenus.']]],
 trainingTitle:['从学会工具，<br>到做出作品。','From learning tools<br>to making films.','De la découverte des outils<br>à la création de films.'],
 courseLabel:['课程体系','Programmes','Programmes'],courseDetail:['查看课程详情','Explore programme','Découvrir le programme'],
 mentorsTitle:['做项目的人，<br>也教你做项目。','Learn from people<br>who make it happen.','Apprendre auprès de celles<br>et ceux qui réalisent.'],
 mentorsIntro:['五位项目实战型导师，覆盖制作、工作流、商业交付与内容出海。导师按课程需求与排期组合。','Five practice-led instructors spanning production, workflows, commercial delivery and international content. Instructors are matched to the programme and availability.','Cinq intervenants de terrain : production, workflows, réalisation commerciale et contenus internationaux. Leur participation dépend du programme et des disponibilités.'],
 mentorLink:['认识导师团队','Meet the instructors','Rencontrer les intervenants'],expertise:['擅长方向','Areas of expertise','Domaines d’expertise'],
 outcome:['学习目标与成果','Learning goals & outputs','Objectifs & réalisations'],audience:['适合谁','Who it is for','À qui s’adresse ce programme'],format:['课程形式','Format','Format'],curriculum:['课程路径','Learning path','Parcours pédagogique'],
 trainingNote:['优秀学员可通过作品考核进入创作者储备。项目合作根据实际需求、作品能力与档期匹配，不承诺固定订单或收入。','Strong participants may be considered for the creator network after a portfolio review. Projects depend on client needs, skills and availability; no fixed work or income is guaranteed.','Les participants peuvent rejoindre le vivier de créateurs après évaluation de leurs travaux. Les missions dépendent des besoins, compétences et disponibilités ; aucun volume de travail ni revenu fixe n’est garanti.'],
 aboutTitle:['用技术赋能表达，<br>用内容连接价值。','Technology empowers expression.<br>Content connects value.','La technologie soutient l’expression.<br>Le contenu crée des liens.'],
 aboutText:['元启程是一家 AIGC 内容产业服务商，以 AI 科技为驱动、文化创意为表达，提供内容制作、实战培训与内容出海启动支持。','AUROVOY is an AIGC content services company bringing AI technology and cultural creativity together through production, practical training and international launch support.','AUROVOY est une société de services de contenu AIGC qui associe technologie IA et créativité culturelle à travers la production, la formation pratique et l’accompagnement à l’international.'],
 aboutTeam:['我们以轻量核心团队与项目制专业伙伴协作，围绕真实需求完成方案、制作、统筹与质量控制，在每一次交付中积累经验。','A lean core team works with project-based specialists on planning, production, coordination and quality control, building experience through real delivery.','Une équipe centrale resserrée collabore avec des spécialistes par projet pour la conception, la production, la coordination et le contrôle qualité.'],
 values:[['专业','创新','温度','共创','成长'],['Expertise','Innovation','Care','Co-creation','Growth'],['Expertise','Innovation','Attention','Co-création','Progression']],
 contactIntro:['商业影像、AI 漫剧、企业内训、渠道合作或内容出海。欢迎从一封邮件开始。','Commercial films, AI drama, corporate training, partnerships or international content. Let’s start with an email.','Films commerciaux, fictions IA, formations, partenariats ou contenus internationaux. Commençons par un e-mail.'],
 briefTitle:['邮件里可以先告诉我们','A helpful starting brief','Pour préparer votre demande'],
 briefItems:[['你想制作什么，或解决什么问题','面向的受众、使用平台与语言','预计周期、内容数量与预算范围'],['What you want to create or the problem to solve','Your audience, platforms and required languages','Timeline, content volume and budget range'],['Votre projet ou le problème à résoudre','Votre public, vos plateformes et les langues souhaitées','Le calendrier, le volume de contenu et le budget envisagé']],
 send:['发送合作邮件','Email us','Nous écrire'],subject:['AUROVOY 项目合作咨询','AUROVOY — Project enquiry','AUROVOY — Demande de collaboration'],
 globalTitle:['让本土创意，<br>找到下一站。','Help local stories<br>find their next audience.','Offrir aux récits locaux<br>une nouvelle destination.'],
 globalScope:['服务聚焦诊断、路径规划、方案设计与专业资源协同。长期运营、投流、客服与发行由对应专业伙伴承接。','The service focuses on diagnosis, planning, solution design and specialist coordination. Ongoing operations, paid media, customer support and distribution are handled by relevant partners.','Le service couvre le diagnostic, la planification, la conception et la coordination de spécialistes. L’exploitation continue, la publicité, le support client et la distribution relèvent des partenaires concernés.'],
 footerLine:['连接文化 · 科技赋能 · 启程未来','Culture connects. Technology enables. The journey begins.','Relier les cultures. Donner les moyens. Ouvrir la voie.']
};
export const courses=[
 {id:'intro',number:'01',name:['AI 漫剧商业公开课','AI Drama: An Introduction','Découverte de la fiction IA'],time:['90–120 分钟','90–120 minutes','90–120 minutes'],audience:['社群用户、机构学员与园区活动人群。','Communities, education groups and innovation-hub audiences.','Communautés, apprenants en institution et publics de pôles d’innovation.'],desc:['从案例与制作流程出发，建立对 AI 漫剧创作与商业应用的整体认识。','Build an overview of AI drama creation and commercial uses through examples and production workflows.','Comprendre la création de fictions IA et ses usages commerciaux à partir d’exemples et de processus de production.'],results:[['了解内容形态与应用场景','认识完整制作流程','明确下一步学习方向'],['Understand formats and use cases','Discover the production workflow','Identify your next learning steps'],['Comprendre formats et usages','Découvrir la chaîne de production','Définir la suite de son apprentissage']]},
 {id:'bootcamp',number:'02',name:['7 天 AI 漫剧实战训练营','7-Day AI Drama Workshop','Atelier pratique de fiction IA en 7 jours'],time:['7 天','7 days','7 jours'],audience:['零基础创作者、短视频从业者与 AI 转型人群。','New creators, short-form video professionals and people moving into AI production.','Créateurs débutants, professionnels de la vidéo courte et personnes en transition vers la production IA.'],desc:['从一个想法到一条完整作品。围绕选题、剧本、角色、分镜、动态、声音与剪辑开展实操。','Take an idea through story, characters, storyboards, motion, sound and editing to a complete film.','Faire évoluer une idée vers un film complet : sujet, scénario, personnages, storyboard, animation, son et montage.'],results:[['以完成 30 秒至 3 分钟作品为目标','沉淀角色卡、场景资产与分镜表','获得阶段点评与结营复盘'],['Aim to complete a 30-second to 3-minute film','Build character sheets, scene assets and a storyboard','Receive stage reviews and a final debrief'],['Viser un film de 30 secondes à 3 minutes','Créer fiches personnages, décors et storyboard','Bénéficier de retours par étape et d’un bilan final']]},
 {id:'enterprise',number:'03',name:['企业与机构 AIGC 内训','Tailored AIGC Training','Formation AIGC sur mesure'],time:['1–3 天 / 按需','1–3 days / tailored','1–3 jours / sur mesure'],audience:['企业、园区、MCN、内容机构与培训机构。','Businesses, innovation hubs, MCNs, content studios and training providers.','Entreprises, pôles d’innovation, réseaux de créateurs, studios et organismes de formation.'],desc:['围绕真实业务设计课程，在 AI 视频、漫剧、数字人或内容工作流中选配实操模块。','Design practical modules around real business needs in AI video, drama, digital presenters or content workflows.','Construire des modules pratiques autour des besoins métier : vidéo IA, fiction, présentateurs numériques ou workflows.'],results:[['围绕业务形成内容样板','建立可复用的团队方法','按需求配置导师与课程模块'],['Develop a business-relevant content example','Establish reusable team methods','Match instructors and modules to your needs'],['Produire un exemple adapté au métier','Établir des méthodes réutilisables en équipe','Adapter les intervenants et modules aux besoins']]}
];
export const days=[
 [['选题与方向','选题卡与项目目标'],['Story & direction','Topic card and project goals'],['Sujet & direction','Fiche sujet et objectifs']],
 [['剧本与节奏','短剧本与剧情结构'],['Script & pacing','Short script and story structure'],['Scénario & rythme','Scénario court et structure narrative']],
 [['角色与资产','角色卡与场景资产'],['Characters & assets','Character sheets and scene assets'],['Personnages & ressources','Fiches personnages et décors']],
 [['分镜与镜头','完整分镜表'],['Storyboards & shots','A complete storyboard'],['Storyboard & plans','Un storyboard complet']],
 [['动态与视频','核心动态镜头'],['Motion & video','Key moving shots'],['Animation & vidéo','Plans animés principaux']],
 [['声音与剪辑','可观看初版成片'],['Sound & editing','A watchable first cut'],['Son & montage','Une première version du film']],
 [['成片与复盘','完整作品与点评'],['Delivery & review','Finished film and feedback'],['Finalisation & bilan','Film finalisé et retours']]
];
export const mentors=[
 {id:'sophie',name:['Sophie','Sophie','Sophie'],role:['AI 内容出海制片人 · OPC 项目孵化导师','International AI Content Producer · Project Incubation Instructor','Productrice de contenus IA internationaux · Accompagnement de projets'],bio:['英国 MBA / PMP，具备大型企业项目管理背景。专注 AI 微电影定制、漫剧项目统筹、商业订单交付与跨团队协作，将创意拆解为清晰的执行路径。','With a UK MBA, PMP certification and a corporate project-management background, Sophie focuses on bespoke AI films, drama production, commercial delivery and cross-team coordination.','Titulaire d’un MBA britannique et de la certification PMP, Sophie s’appuie sur son expérience en gestion de projets pour coordonner films IA sur mesure, fictions et productions commerciales.'],tags:[['项目管理','内容出海','商业交付'],['Project management','International content','Commercial delivery'],['Gestion de projets','Contenus internationaux','Réalisation commerciale']]},
 {id:'jiang',name:['姜老师','Jiang','Jiang'],role:['AIGC 智能体工作流导师 · AI 内容生产实战导师','AIGC Agent Workflows · Practical Content Production','Workflows d’agents AIGC · Production pratique de contenu'],bio:['把脚本、图像、视频、音频与业务流程连接起来，帮助学员从单点工具操作走向可复用的内容生产流程。课程覆盖智能体应用、自动化内容生产与企业提效。','Connects scripts, images, video, audio and business processes, helping learners move from isolated tools to repeatable production workflows, agent applications and automation.','Relie scénarios, images, vidéo, audio et processus métier pour passer d’outils isolés à des workflows réutilisables, intégrant agents et automatisation.'],tags:[['智能体应用','自动化工作流','企业提效'],['AI agents','Workflow automation','Team efficiency'],['Agents IA','Automatisation','Efficacité des équipes']]},
 {id:'bell',name:['贝尔','Bell','Bell'],role:['AI 商业影像总导演 · AI 海外剧项目操盘手','AI Commercial Film Director · International Drama Producer','Réalisateur de films commerciaux IA · Producteur de fictions internationales'],bio:['结合传统商业影像经验与 AI 制作工具，覆盖品牌广告、电商产品、政企宣传与海外剧制作，关注创意策划、制作调度与成片交付之间的衔接。','Combines commercial filmmaking experience with AI tools across brand advertising, product videos, institutional communication and international drama, connecting creative planning with delivery.','Associe l’expérience de l’image commerciale aux outils IA pour la publicité, les vidéos produit, la communication institutionnelle et les fictions internationales.'],tags:[['商业影像','海外短剧','电商内容'],['Commercial films','International drama','Commerce content'],['Films commerciaux','Fictions internationales','Contenus e-commerce']]},
 {id:'yang',name:['子飞','Zifei','Zifei'],role:['AI 漫剧 OPC 孵化导师 · AI 内容实训基地操盘导师','AI Drama & OPC Incubation · Practical Training','Fiction IA & incubation OPC · Formation pratique'],bio:['将传统编导的视听语言转化为 AI 漫剧可执行的方法，围绕选题、剧本、角色、镜头、声音和剪辑开展全流程训练，并支持个人项目孵化与作品评审。','Translates cinematic language into practical AI drama methods, covering story, scripts, characters, shots, sound and editing alongside individual project development and portfolio review.','Transforme le langage cinématographique en méthodes concrètes pour la fiction IA : sujets, scénarios, personnages, plans, son, montage et évaluation des travaux.'],tags:[['导演思维','全流程实训','项目孵化'],['Directing','End-to-end practice','Project incubation'],['Mise en scène','Pratique complète','Incubation de projets']]},
 {id:'huohuo',name:['火火','Huohuo','Huohuo'],role:['AI 实体商业增长导师 · 智能体获客系统导师','AI Local Business Growth · Customer Acquisition Workflows','Croissance des commerces par l’IA · Parcours d’acquisition'],bio:['聚焦实体商家的内容生产与获客场景，结合提示词、数字人、智能体和同城内容运营，帮助企业与个人工作室建立可持续使用的内容方法。','Focuses on content and customer-acquisition needs for local businesses, combining prompting, digital presenters, agents and local content operations into reusable methods.','Se concentre sur les besoins des commerces locaux en matière de contenu et d’acquisition, en associant prompts, présentateurs numériques, agents et communication de proximité.'],tags:[['实体商业','数字人内容','智能体应用'],['Local business','Digital presenters','AI agents'],['Commerces locaux','Présentateurs numériques','Agents IA']]}
];
