// Course structure follows the supplied training plan; exercises make each module concrete.
export const curricula={
 intro:[
  [['认识内容与应用','比较 AI 漫剧、产品短片、企业 IP 与数字人口播，理解不同内容解决什么问题。','从个人或业务需求中选一个方向，写下目标受众。','一张内容方向卡'],['Formats and uses','Compare AI drama, product films, corporate IP and digital presenters through the needs they address.','Choose a personal or business direction and define its audience.','A content direction card'],['Formats et usages','Comparer fiction IA, films produit, IP d’entreprise et présentateurs numériques selon leurs usages.','Choisir une piste personnelle ou professionnelle et définir son public.','Une fiche d’orientation']],
  [['拆解一支短片','从主题、画面、镜头衔接与声音入手，观察一支作品如何组织信息和情绪。','观看学员练习案例，记录开场、主体与收尾各自的作用。','一份案例观察清单'],['Read a short film','Examine how theme, images, transitions and sound organise information and emotion.','Watch a learner exercise and note the roles of opening, development and ending.','A film observation checklist'],['Lire un film court','Observer comment thème, images, transitions et son organisent information et émotion.','Analyser le rôle de l’ouverture, du développement et de la conclusion d’un exercice.','Une grille d’observation']],
  [['走通制作流程','按创意、脚本、视觉资产、动态、声音、剪辑与输出的顺序讲解制作链路。','跟随流程示范，将一个简单想法拆成可执行的镜头任务。','一份制作流程图'],['Understand production','Follow an idea through script, visual assets, motion, sound, editing and export.','Use a workflow demonstration to turn a simple idea into shot-level tasks.','A production workflow map'],['Comprendre la production','Suivre une idée du scénario aux ressources visuelles, à l’animation, au son, au montage et à l’export.','Décomposer une idée en tâches par plan à partir d’une démonstration.','Un schéma de production']],
  [['判断学习与项目难点','认识人物一致性、动作稳定性、素材使用、修改沟通与交付要求等常见问题。','对照自己的方向，找出当前最需要补齐的一项能力。','一张能力差距清单'],['Identify the challenges','Discuss character consistency, motion stability, asset use, revision and delivery requirements.','Identify the most useful skill to develop for your chosen direction.','A skills gap checklist'],['Identifier les difficultés','Aborder cohérence des personnages, stabilité des mouvements, ressources, corrections et livraison.','Repérer la compétence prioritaire pour la direction choisie.','Une liste de compétences à développer']],
  [['制定下一步计划','区分入门体验、完整作品训练与企业场景实操，回答现场问题。','明确第一个练习题目，以及希望完成的作品形式。','个人学习起点与练习计划'],['Plan your next step','Compare introductory practice, full-film training and business-focused workshops, followed by questions.','Define a first exercise and the format you want to create.','A personal starting point and practice plan'],['Préparer la suite','Distinguer découverte, réalisation complète et pratique métier, puis répondre aux questions.','Définir un premier exercice et le format à réaliser.','Un point de départ et un plan de pratique']]
 ],
 bootcamp:[
  [['选题与商业方向','认识常见题材、受众与内容形态，确定作品的核心看点与制作范围。','完成选题卡，写明人物、目标受众和预计时长。','选题卡与项目目标'],['Story direction','Explore genres, audiences and formats to define the film’s central appeal and production scope.','Write a topic card with characters, audience and target duration.','Topic card and project goals'],['Sujet et direction','Explorer genres, publics et formats pour définir l’intérêt central et le périmètre du film.','Rédiger une fiche avec personnages, public et durée visée.','Fiche sujet et objectifs']],
  [['剧本与节奏','围绕开场钩子、人物动机、核心冲突和结尾，搭建短叙事结构。','把梗概扩展为可制作的短剧本，标注对白与关键动作。','短剧本与剧情结构'],['Script and pacing','Build a short narrative around an opening hook, motivation, conflict and ending.','Expand the outline into a producible script with dialogue and key actions.','Short script and story structure'],['Scénario et rythme','Construire un récit autour de l’accroche, des motivations, du conflit et de la conclusion.','Développer un scénario réalisable avec dialogues et actions clés.','Scénario court et structure']],
  [['角色与视觉资产','学习角色外观、服装、表情和场景设定，建立统一风格与一致性参考。','制作角色卡和场景参考，整理命名与版本。','角色卡与场景资产'],['Characters and assets','Define appearance, clothing, expressions and settings with consistent visual references.','Create character sheets and scene references with clear names and versions.','Character sheets and scene assets'],['Personnages et ressources','Définir apparence, costumes, expressions et décors avec des références cohérentes.','Créer fiches personnages et références de décors, puis organiser noms et versions.','Fiches personnages et décors']],
  [['分镜与镜头设计','把剧本拆成景别、构图、动作和镜头时长，理解镜头间的衔接。','完成分镜表，检查每个镜头是否推动故事。','完整分镜表'],['Storyboards and shots','Translate the script into shot sizes, composition, action and duration, with clear transitions.','Build a storyboard and check how each shot advances the story.','A complete storyboard'],['Storyboard et plans','Traduire le scénario en cadrages, compositions, actions et durées, avec des transitions claires.','Construire un storyboard et vérifier l’utilité narrative de chaque plan.','Un storyboard complet']],
  [['动态与 AI 视频','练习图生视频、关键帧、人物动作与运镜，判断和处理常见生成问题。','生成核心动态镜头，筛选可用版本并记录修改点。','核心动态镜头'],['Motion and AI video','Practise image-to-video, keyframes, character action and camera movement while diagnosing common errors.','Generate core moving shots, select usable takes and record revisions.','Core moving shots'],['Animation et vidéo IA','Pratiquer image-vers-vidéo, images clés, actions et mouvements de caméra en identifiant les défauts.','Générer les plans principaux, choisir les prises et noter les corrections.','Plans animés principaux']],
  [['声音与剪辑','整合配音、音乐、音效、字幕与基础包装，用剪辑建立完整节奏。','把镜头和声音连接成初剪，检查对白、字幕与画面配合。','可观看的初版成片'],['Sound and editing','Combine voices, music, sound effects, subtitles and titles into a coherent edit.','Assemble a first cut and check dialogue, subtitles and image alignment.','A watchable first cut'],['Son et montage','Assembler voix, musique, bruitages, sous-titres et titres dans un montage cohérent.','Réaliser une première version et vérifier voix, sous-titres et images.','Une première version du film']],
  [['成片与作品复盘','围绕叙事完成度、视觉一致性、声音与输出规范进行检查和点评。','根据反馈修改作品，输出成片并整理创作说明。','以完成 30 秒至 3 分钟作品为目标'],['Final film and review','Review narrative completeness, visual consistency, sound and export quality.','Revise with feedback, export the film and prepare a creative note.','Aim for a finished film of 30 seconds to 3 minutes'],['Finalisation et bilan','Évaluer récit, cohérence visuelle, son et qualité de l’export.','Corriger selon les retours, exporter et préparer une note de création.','Viser un film de 30 secondes à 3 minutes']]
 ],
 enterprise:[
  [['业务需求与内容选题','明确受众、传播场景、品牌语气与交付规格，选择适合课堂实操的真实任务。','将一个业务需求整理为内容简报。','企业内容简报'],['Business brief','Define audience, context, brand voice and delivery requirements for a practical business task.','Turn one business need into a content brief.','A business content brief'],['Brief métier','Définir public, contexte, ton de marque et livrables pour un cas pratique.','Transformer un besoin métier en brief de contenu.','Un brief métier']],
  [['品牌 IP 与视觉规范','围绕企业 IP、角色或产品建立视觉参考，学习如何控制风格与信息准确性。','整理角色设定、场景参考和视觉检查项。','角色或产品视觉参考表'],['Brand IP and visuals','Build visual references for a corporate character or product, maintaining style and accurate information.','Prepare character settings, scene references and visual checks.','A character or product reference sheet'],['IP et identité visuelle','Créer des références pour un personnage ou un produit en respectant style et exactitude.','Préparer personnages, décors et points de contrôle visuel.','Une fiche de références visuelles']],
  [['脚本与场景化表达','将企业介绍、产品卖点或服务流程转化为简洁的脚本和镜头设计。','完成一个企业内容短脚本及分镜。','短脚本与分镜方案'],['Script and context','Translate a company introduction, product feature or service process into a concise script and shot plan.','Write and storyboard one piece of business content.','Short script and storyboard'],['Scénario et contexte','Transformer présentation d’entreprise, atouts produit ou service en scénario et plans concis.','Écrire et découper un contenu métier.','Scénario et storyboard']],
  [['AI 影像与声音制作','按业务需要选配 AI 视频、数字人口播、配音与剪辑练习。','围绕选定方案完成核心镜头或一段可演示的样板。','业务内容样板'],['AI image and sound','Select AI video, digital presenter, voice and editing exercises to match the business need.','Produce core shots or a demonstrable prototype from the chosen brief.','A business content prototype'],['Image et son IA','Choisir des exercices de vidéo IA, présentateur numérique, voix et montage selon les besoins.','Produire des plans clés ou un prototype présentable.','Un prototype de contenu métier']],
  [['团队工作流与协作','串联脚本、图像、视频、音频与反馈环节，明确分工、文件命名和版本管理。','绘制当前流程，识别可复用的模板和自动化环节。','团队流程图与任务分工'],['Team workflow','Connect scripts, images, video, audio and feedback with roles, naming and version management.','Map the workflow and identify reusable templates and automation opportunities.','A workflow map and role allocation'],['Workflow d’équipe','Relier scénario, images, vidéo, audio et retours avec rôles, noms de fichiers et versions.','Cartographier le processus et repérer modèles réutilisables et automatisations.','Un workflow et une répartition des rôles']],
  [['质量检查与业务复盘','检查信息准确性、品牌一致性、素材使用和成片规格，梳理下一轮改进。','评审样板并建立适合团队的检查清单。','样板复盘与交付检查清单'],['Quality and review','Check information, brand consistency, asset use and output specifications to plan improvements.','Review the prototype and create a team checklist.','Prototype review and delivery checklist'],['Qualité et bilan','Vérifier informations, cohérence de marque, ressources et formats pour préparer les améliorations.','Évaluer le prototype et établir une grille d’équipe.','Bilan et grille de livraison']]
 ]
};
export const courseCases={
 intro:{asset:'tea',name:['霸王茶姬','CHAGEE','CHAGEE'],label:['学员练习作品，非商业合作','Student practice work — not a commercial collaboration','Exercice d’apprenant — sans collaboration commerciale'],intro:['从山野氛围到饮品表达，观察画面如何建立情绪、主题与产品联想。','Observe how landscapes and beverage imagery create mood, theme and product associations.','Observer comment paysages et images de boisson créent atmosphère, thème et associations produit.']},
 bootcamp:{asset:'awakening',name:['雷羽觉醒','Thunder Feather Awakening','L’Éveil des plumes de foudre'],label:['学员案例','Learner work','Réalisation d’apprenant'],intro:['围绕角色成长与奇幻视觉，观察人物设定、动态镜头和剪辑节奏如何形成一段完整叙事。','See how character design, moving shots and editing create a fantasy narrative centred on growth.','Observer comment personnages, plans animés et montage forment un récit fantastique autour de la progression.']},
 enterprise:{asset:'enterprise-training',name:['企业 AIGC 工作坊','Corporate AIGC Workshop','Atelier AIGC en entreprise'],label:['企业内训主题示意','Corporate training illustration','Illustration de formation en entreprise'],intro:['围绕团队真实业务展开内容制作与流程协作训练。','Content production and workflow practice around real business needs.','Production de contenu et collaboration autour de besoins métier réels.']}
};
