const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function enhancePage(body,file,c){
 const {t,u,asset,films,categories,courses,filmGroups,categoryCard}=c;
 const tabs=(id,labels,panels)=>`<div class="experience-tabs" data-tabs><div class="experience-tablist js-only" role="tablist">${labels.map((label,i)=>`<button type="button" role="tab" id="${id}-tab-${i}" aria-controls="${id}-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${esc(label)}<span aria-hidden="true">↗</span></button>`).join('')}</div>${panels.map((panel,i)=>`<div class="experience-panel" id="${id}-panel-${i}" role="tabpanel" aria-labelledby="${id}-tab-${i}" tabindex="0">${panel}</div>`).join('')}</div>`;
 if(file==='works.html'){
  const controls=`<div class="work-tools"><label class="work-search">${t(['搜索作品','Search films','Rechercher un film'])}<input type="search" name="search" data-work-search placeholder="${t(['输入片名或关键词','Title or keyword','Titre ou mot-clé'])}" autocomplete="off"></label><label>${t(['内容品类','Category','Catégorie'])}<select data-work-category><option value="all">${u('viewAll')}</option>${categories.map(cat=>`<option value="${cat.id}">${esc(t(cat.name))}</option>`).join('')}</select></label><label>${t(['画面方向','Orientation','Orientation'])}<select data-work-format><option value="all">${t(['全部画幅','All formats','Tous les formats'])}</option><option value="landscape">${t(['横版','Landscape','Horizontal'])}</option><option value="portrait">${t(['竖版','Portrait','Vertical'])}</option></select></label><button type="button" class="filter-reset" data-work-reset>${t(['重置','Reset','Réinitialiser'])}</button></div>`;
  const search=`<div data-work-browser>${controls}<div data-work-results>${filmGroups(films.map(f=>f.id))}</div><p class="work-empty" data-work-empty hidden>${t(['暂未找到匹配作品 试试其他关键词或清除筛选','No matching films Try another keyword or reset the filters','Aucun film correspondant Essayez un autre mot-clé ou réinitialisez les filtres'])}</p><p class="sr-only" aria-live="polite" data-work-status></p></div>`;
  body=body.replace(/<section class="section category-section">[\s\S]*?<\/section>/,`<section class="section category-section work-studio">${tabs('work-view',t([['浏览品类','查找作品'],['Explore categories','Find a film'],['Explorer les catégories','Trouver un film']]),[`<div class="category-grid">${categories.map(categoryCard).join('')}</div>`,search])}</section>`);
 }
 if(file==='training.html'){
  const labels=t([['初次接触 AI 创作','希望独立完成作品','用于团队真实业务'],['New to AI creation','Ready to make a film','Building a team workflow'],['Découvrir la création IA','Réaliser un premier film','Former une équipe']]);
  const panels=courses.map(course=>`<div class="recommendation"><div><p class="eyebrow">${t(['适合你的学习起点','YOUR STARTING POINT','VOTRE POINT DE DÉPART'])}</p><h3>${t(course.name)}</h3><p>${t(course.audience)}</p></div><div><ul>${t(course.results).map(x=>`<li>${x}</li>`).join('')}</ul><a class="text-link" href="course-${course.id}.html">${u('courseDetail')} ↗</a></div></div>`);
  body=body.replace('<section class="section course-section">',`<section class="section learning-explorer"><div class="experience-heading"><p class="eyebrow">LEARN BY MAKING</p><h2>${t(['从你的目标开始','Start with your goal','Partir de votre objectif'])}</h2></div>${tabs('learning-path',labels,panels)}</section><section class="section course-section">`);
 }
 if(file==='global.html'){
  const paths=[
   {label:['已有内容作品','I have existing content','J’ai déjà des contenus'],title:['让作品适配下一站','Adapt your work for its next audience','Adapter vos œuvres à un nouveau public'],intro:['从已有样片、剧本或 IP 出发，梳理目标受众、内容语境与本地化需求。','Start with your films, scripts or IP to define audiences, cultural context and localisation needs.','Partir de vos films, scénarios ou IP pour préciser public, contexte culturel et besoins de localisation.'],items:[['准备作品与版权信息','讨论语言与平台方向','形成适配范围与协作清单'],['Gather content and rights information','Discuss languages and platforms','Define adaptation scope and specialist needs'],['Rassembler contenus et informations sur les droits','Choisir langues et plateformes','Définir les adaptations et les besoins en spécialistes']]},
   {label:['准备启动新项目','I am starting a project','Je lance un projet'],title:['把想法变成启动方案','Turn an idea into a launch plan','Transformer une idée en plan de lancement'],intro:['从内容类型、目标市场与预算出发，厘清创作、技术与制作资源的优先次序。','Begin with format, market and budget to prioritise creative, technical and production resources.','Partir du format, du marché et du budget pour hiérarchiser les ressources créatives, techniques et de production.'],items:[['梳理项目目标与受众','规划内容和产品路径','确认团队预算与排期'],['Define objectives and audiences','Plan content and product direction','Outline team, budget and schedule'],['Préciser objectifs et public','Planifier contenu et produit','Définir équipe, budget et calendrier']]},
   {label:['拓展团队海外业务','My team is expanding','Mon équipe se développe'],title:['让团队协作跨越语言','Build collaboration across languages','Faire collaborer les équipes au-delà des langues'],intro:['围绕现有团队和业务基础，明确内部分工、外部专业伙伴与阶段交付标准。','Build on your team and business to define responsibilities, specialist partners and delivery milestones.','S’appuyer sur votre équipe et votre activité pour définir rôles, partenaires spécialisés et étapes de réalisation.'],items:[['了解当前内容生产流程','匹配本地化与专业资源','设计阶段验收和沟通机制'],['Review the current production workflow','Identify localisation and specialist resources','Define reviews and communication routines'],['Examiner le workflow de production','Identifier les ressources de localisation','Définir validations et échanges']]}
  ];
  const panels=paths.map(p=>`<div class="route-plan"><div><p class="eyebrow">GLOBAL START</p><h3>${t(p.title)}</h3><p>${t(p.intro)}</p><a class="text-link" href="works-overseas.html">${t(['探索海外短剧作品','Explore international drama','Explorer les fictions internationales'])} ↗</a></div><ol>${t(p.items).map((x,i)=>`<li><span>0${i+1}</span>${x}</li>`).join('')}</ol></div>`);
  body=body.replace('<section class="section"><div class="split-content">',`<section class="section global-explorer"><div class="experience-heading"><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>${t(['你的出海从哪里开始','Where does your journey begin','Où commence votre parcours'])}</h2></div>${tabs('global-route',paths.map(p=>t(p.label)),panels)}</section><section class="section"><div class="split-content">`);
 }
 if(file==='about.html'){
  const values=[
   {name:['文化','Culture','Culture'],title:['让表达有自己的语言','Give expression its own language','Donner un langage à chaque expression'],text:['从故事、情感与审美出发，让内容承载清晰的创作意图。技术带来新的制作方式，人的观察与判断决定内容的方向。','Stories, emotion and visual craft give content a clear creative purpose. Technology opens new methods; human observation and judgement give them direction.','Récit, émotion et esthétique donnent au contenu une intention claire. La technologie ouvre de nouvelles méthodes ; le regard et le jugement humains leur donnent une direction.']},
   {name:['科技','Technology','Technologie'],title:['让创意进入可执行的流程','Make creativity part of a workable process','Inscrire la créativité dans un processus concret'],text:['将脚本、视觉、动态、声音与剪辑连接起来，用适合项目的工具和专业协作，推进从想法到成片的每一步。','Connect scripts, visuals, motion, sound and editing with the tools and specialists each project needs, moving from the first idea to the final film.','Relier scénario, image, animation, son et montage avec les outils et spécialistes adaptés à chaque étape, de l’idée au film final.']},
   {name:['连接','Connection','Lien'],title:['让内容抵达新的受众','Help content reach new audiences','Permettre au contenu de rencontrer de nouveaux publics'],text:['连接创作者、企业与专业伙伴，在内容交付、人才成长和跨语言协作中，探索长期合作的可能。','Connect creators, businesses and specialists through production, learning and multilingual collaboration, exploring lasting ways to work together.','Relier créateurs, entreprises et spécialistes par la production, l’apprentissage et la collaboration multilingue pour construire des relations durables.']}
  ];
  body=body.replace(/<section class="section about-paths">[\s\S]*?<\/section>/,`<section class="section brand-dialogue"><div class="experience-heading"><p class="eyebrow">CULTURE TECHNOLOGY CONNECTION</p><h2>${t(['我们如何理解创作','How we approach creativity','Notre approche de la création'])}</h2></div>${tabs('brand-values',values.map(v=>t(v.name)),values.map(v=>`<div class="brand-value-panel"><h3>${t(v.title)}</h3><p>${t(v.text)}</p></div>`))}</section>`);
 }
 if(file==='contact.html'){
  const form=`<div class="contact-brief"><form class="brief-builder" data-brief-form><h2>${t(['把想法整理成项目需求','Shape your project brief','Préparer votre demande'])}</h2><p class="brief-note">${t(['填写后可打开邮件草稿 内容由你确认后发送','Create an email draft to review and send yourself','Créez un brouillon à vérifier et à envoyer vous-même'])}</p><label>${t(['合作方向','Project type','Type de projet'])}<select name="projectType">${['production','training','global'].map(k=>`<option>${u(k)}</option>`).join('')}</select></label><label>${t(['项目想法','Your idea','Votre idée'])}<textarea name="idea" rows="4" maxlength="3000" required placeholder="${t(['例如 希望为品牌制作一支有故事感的短片','For example A story-led short film for our brand','Par exemple Un court film narratif pour notre marque'])}"></textarea></label><label>${t(['期望时间','Target timing','Échéance souhaitée'])}<input type="text" name="timing" maxlength="120" placeholder="${t(['可选','Optional','Facultatif'])}"></label><div class="brief-actions"><button type="submit" class="button dark">${t(['打开邮件草稿','Open email draft','Ouvrir le brouillon'])}<span aria-hidden="true">↗</span></button><button type="button" class="text-link" data-copy-brief>${t(['复制需求','Copy brief','Copier la demande'])}</button></div><p class="brief-status" data-brief-status role="status"></p></form></div>`;
  const start=body.indexOf('<div class="contact-brief">'),end=body.indexOf('</section>',start);
  if(start>=0&&end>=0)body=body.slice(0,start)+form+body.slice(end);
 }
 return body;
}
