import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {languages,email,categories,films,removedFilmIds,ui,courses,days,mentors} from './content.mjs';
import {mentorDetails} from './mentor-details.mjs';
import {enhancePage} from './experience.mjs';
import {polishPage,pageClass} from './editorial.mjs';
import {deepenPage} from './brand-depth.mjs';
import {refineLearning} from './learning-pages.mjs';
import {logoExplorer} from './complete-logo.mjs';
import {addParentNavigation} from './page-navigation.mjs';
const project=path.dirname(fileURLToPath(import.meta.url));
const root=path.join(project,'src'),origin='https://aurovoy.invalid';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let media={};if(fs.existsSync(path.join(project,'media-info.json')))media=Object.fromEntries(JSON.parse(fs.readFileSync(path.join(project,'media-info.json'),'utf8')).map(x=>[x.id,x]));
const layout=JSON.parse(fs.readFileSync(path.join(project,'media-layout.json'),'utf8'));
const isPortrait=id=>layout[id].portrait;
// Remove only the explicitly withdrawn generated pages and media from current output.
for(const dir of [root,path.join(project,'dist')])for(const id of removedFilmIds){
 for(const relative of [...['','en','fr'].map(l=>path.join(l,`work-${id}.html`)),...['mp4','webp'].map(ext=>`assets/film-${id}.${ext}`),`assets/cover-${id}.webp`]){
  const file=path.resolve(dir,relative);if(!file.startsWith(path.resolve(dir)+path.sep))throw new Error('Invalid removal target');
  if(fs.existsSync(file))fs.unlinkSync(file);
 }
}
for(const dir of [root,path.join(project,'dist')])for(const lang of ['','en','fr']){
 const file=path.resolve(dir,lang,'services.html');
 if(!file.startsWith(path.resolve(dir)+path.sep))throw new Error('Invalid removal target');
 if(fs.existsSync(file))fs.unlinkSync(file);
}
let total=0;
for(const [li,lang] of languages.entries()){
 const t=v=>v[li],u=k=>t(ui[k]),prefix=lang==='zh'?'':'../',asset=f=>`${prefix}assets/${f}`;
 const navNames=t(ui.nav),navFiles=['index.html','works.html','global.html','training.html','about.html','contact.html'];
 const cleanHeading=text=>text.split(/(<[^>]+>)/g).map(part=>part.startsWith('<')?part:part
   .replace(/&amp;|&/g,[' 与 ',' and ',' et '][li])
   .replace(/(\d):(\d)/g,['$1 比 $2','$1 by $2','$1 sur $2'][li])
   .replace(/[，。！？、：；“”「」『』（）()!?;:,\/·×—–]/g,' ')
   .replace(/\.(?=\s|$)/g,'').replace(/\s{2,}/g,' ')).join('').trim();
 const cleanTitles=markup=>markup.replace(/(<h[1-3]\b[^>]*>)([\s\S]*?)(<\/h[1-3]>)/g,(_,a,b,c)=>a+cleanHeading(b)+c)
   .replace(/(<(?:p|span) class="eyebrow">)([\s\S]*?)(<\/(?:p|span)>)/g,(_,a,b,c)=>a+cleanHeading(b)+c);
 const mail=()=>`mailto:${email}?subject=${encodeURIComponent(u('subject'))}`;
 const button=(href,label)=>`<a class="button dark" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
 const tags=a=>`<div class="tags">${a.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;
 const crumbs=a=>`<nav class="breadcrumbs" aria-label="${t(['当前位置','Breadcrumb','Fil d’Ariane'])}"><a href="index.html">${navNames[0]}</a>${a.map(([label,href])=>`<span aria-hidden="true">/</span>${href?`<a href="${href}">${label}</a>`:`<span aria-current="page">${label}</span>`}`).join('')}</nav>`;
 const title=(tag,h,p='',bc=[],extra='')=>`<section class="page-head section">${crumbs(bc)}<p class="eyebrow">${tag}</p><div class="page-heading"><h1>${h}</h1>${p?`<p>${p}</p>`:''}</div>${extra}</section>`;
 function page(file,name,body,active=''){
  const context={li,t,u,asset,films,categories,courses,filmGroups,categoryCard};
  body=cleanTitles(logoExplorer(refineLearning(deepenPage(polishPage(enhancePage(body,file,context),file,context),file,context),file,context),file,context));
  body=addParentNavigation(body,file,context);
  const dest=path.join(root,lang==='zh'?'':lang,file);fs.mkdirSync(path.dirname(dest),{recursive:true});
  const alternatives=languages.map((l,i)=>`<a href="${prefix}${l==='zh'?'':l+'/'}${file}" lang="${l}" hreflang="${l}"${l===lang?' aria-current="page"':''}>${['中文','English','Français'][i]}<span>${l===lang?'✓':''}</span></a>`).join('');
  const canonical=`${origin}/${lang==='zh'?'':lang+'/'}${file==='index.html'?'':file}`;
  const head=`<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#153C6E"><title>${esc(name)} | AUROVOY 元启程</title><meta name="description" content="${esc(u('aboutText'))}"><link rel="canonical" href="${canonical}">${languages.map(l=>`<link rel="alternate" hreflang="${l==='zh'?'zh-CN':l}" href="${origin}/${l==='zh'?'':l+'/'}${file==='index.html'?'':file}">`).join('')}<link rel="stylesheet" href="${prefix}styles.css"><link rel="icon" href="${asset('mark.png')}" type="image/png">`;
  const header=`<a class="skip" href="#main">${u('skip')}</a><header class="header"><a class="brand" href="index.html" aria-label="AUROVOY ${esc(navNames[0])}"><img src="${asset('mark.png')}" alt="" width="56" height="64"><span>AUROVOY <b>元启程</b><small>CULTURE & TECHNOLOGY</small></span></a><nav id="nav" aria-label="${t(['主导航','Main navigation','Navigation principale'])}">${navFiles.map((f,i)=>`<a href="${f}"${active===f?' class="active" aria-current="page"':''}>${navNames[i]}</a>`).join('')}</nav><div class="header-tools"><details class="language"><summary aria-label="${u('language')}"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></svg>${['中文','EN','FR'][li]} <span aria-hidden="true">⌄</span></summary><div class="language-options">${alternatives}</div></details><button class="menu-toggle" aria-label="${u('menu')}" aria-expanded="false" aria-controls="nav">${u('menu')} <span aria-hidden="true">☰</span></button></div></header>`;
  const footer=`<footer class="site-footer"><div><a class="footer-wordmark" href="index.html">AUROVOY <span>元启程</span></a><p>${u('footerLine')}</p></div><div class="footer-contact"><span>${u('emailLabel')}</span><a href="${mail()}">${email} ↗</a></div><div class="footer-bottom"><span>© 2026 AUROVOY</span><span>${u('company')}</span><span>SHENZHEN, CHINA</span></div></footer>`;
  const preferences=`<div class="experience-preferences js-only"><button type="button" data-cursor-toggle aria-pressed="true">${t(['启启鲸光标','Qiqi Whale cursor','Curseur Qiqi'])}<span></span></button><button type="button" data-motion-toggle aria-pressed="true">${t(['动态效果','Motion effects','Animations'])}<span></span></button></div>`;
  const interactiveFooter=footer.replace('<div class="footer-bottom">',preferences+'<div class="footer-bottom">');
  const preview=`<dialog class="preview-dialog" data-preview-dialog aria-labelledby="preview-title"><div class="preview-dialog-header"><h2 id="preview-title">${t(['作品预览','Film preview','Aperçu du film'])}</h2><button type="button" data-preview-close aria-label="${t(['关闭预览','Close preview','Fermer l’aperçu'])}">×</button></div><video controls playsinline preload="none"></video><div class="preview-dialog-footer"><p>${u('preview')}</p><a data-preview-link href="works.html">${t(['查看作品详情','View film details','Voir le détail du film'])} ↗</a></div></dialog>`;
  fs.writeFileSync(dest,`<!doctype html><html lang="${lang==='zh'?'zh-CN':lang}"><head>${head}<link rel="stylesheet" href="${prefix}multipage.css"><link rel="stylesheet" href="${prefix}brand-v3.css"><link rel="stylesheet" href="${prefix}portfolio-v4.css"><link rel="stylesheet" href="${prefix}experience.css"><link rel="stylesheet" href="${prefix}editorial.css"><link rel="stylesheet" href="${prefix}brand-depth.css"><link rel="stylesheet" href="${prefix}learning.css"><link rel="stylesheet" href="${prefix}goal-studio.css"><link rel="stylesheet" href="${prefix}page-navigation.css"></head><body class="lang-${lang} ${pageClass(file)}"><div class="reading-progress" aria-hidden="true"></div>${header}<main id="main">${body}</main>${interactiveFooter}${preview}<script src="${prefix}app.js" defer></script><script src="${prefix}interaction-core.js" defer></script><script src="${prefix}experience.js" defer></script></body></html>`);total++;
 }
 const cta=(short=false)=>`<section class="contact-band section"><p class="eyebrow">${u('emailLabel')}</p><div><h2>${short?u('project'):u('contactCta')}</h2>${button('contact.html',u('write'))}</div></section>`;
 const serviceCards=()=>`<div class="gateway-grid">${[['production','productionDesc','production.html'],['training','trainingDesc','training.html'],['global','globalDesc','global.html']].map(([h,p,href],i)=>`<a class="gateway" href="${href}"><span class="gateway-num">0${i+1}</span><h3>${u(h)}</h3><p>${u(p)}</p><span class="gateway-link">${u('learn')} <b aria-hidden="true">↗</b></span></a>`).join('')}</div>`;
 const filmCard=id=>{const f=films.find(f=>f.id===id),format=isPortrait(id)?'portrait':'landscape';return `<article class="film-tile" data-category="${f.category}" data-format="${format}" data-search="${esc(f.name.join(' '))}"><a class="film-link ${isPortrait(id)?'portrait':''}" href="work-${id}.html"><div class="card-image"><img src="${asset(`cover-${id}.webp`)}" alt="${esc(t(f.name))}" loading="lazy" width="${layout[id].width}" height="${layout[id].height}"><span class="play" aria-hidden="true">▶</span></div><div class="film-title"><h3>${esc(t(f.name))}</h3><span aria-hidden="true">↗</span></div></a><button type="button" class="quick-preview" data-preview data-title="${esc(t(f.name))}" data-src="${asset(`film-${id}.mp4`)}" data-poster="${asset(`cover-${id}.webp`)}" data-href="work-${id}.html" data-format="${format}" aria-label="${esc(t(['预览 ','Preview ','Aperçu '])+t(f.name))}" hidden>${t(['快捷预览','Quick preview','Aperçu rapide'])}</button></article>`};
 const filmGroups=(ids,headingLevel=2)=>'<!--portfolio-start-->'+[false,true].map(portrait=>{const group=ids.filter(id=>isPortrait(id)===portrait);return group.length?`<section class="format-group ${portrait?'format-portrait':'format-landscape'}"><h${headingLevel} class="format-heading">${portrait?t(['竖版作品','Portrait films','Films verticaux']):t(['横版作品','Landscape films','Films horizontaux'])}</h${headingLevel}><div class="film-grid ${portrait?'portrait-grid':'landscape-grid'}">${group.map(filmCard).join('')}</div></section>`:''}).join('')+'<!--portfolio-end-->';
 const categoryCard=c=>`<a class="category-card ${c.id==='avatar'?'portrait':''}" href="works-${c.id}.html"><div class="card-image">${c.id==='avatar'?`<div class="avatar-triptych">${c.films.map(id=>`<img src="${asset(`cover-${id}.webp`)}" alt="" width="406" height="720" loading="lazy">`).join('')}</div>`:`<img src="${asset(`cover-${c.cover}.webp`)}" alt="${esc(t(c.name))}" loading="lazy" width="900" height="562">`}<span class="round-arrow" aria-hidden="true">↗</span></div><div class="category-name"><h2>${t(c.name)}</h2></div><p>${t(c.desc)}</p></a>`;
 const process=()=>`<section class="process section"><p class="eyebrow">${t(['合作流程','HOW WE WORK','NOTRE MÉTHODE'])}</p><h2>${u('processTitle')}</h2><ol>${t(ui.process).map(([h,p],i)=>`<li><span>0${i+1}</span><h3>${h}</h3><p>${p}</p></li>`).join('')}</ol></section>`;
 const courseCard=c=>`<a class="course-card" href="course-${c.id}.html"><span class="eyebrow">${t(c.time)}</span><span class="course-number">${c.id==='bootcamp'?'7':c.number}</span><h3>${t(c.name)}</h3><p>${t(c.desc)}</p><span class="gateway-link">${u('courseDetail')} <b aria-hidden="true">↗</b></span></a>`;
 const mentorCard=m=>`<a class="mentor-link" href="mentor-${m.id}.html"><div class="mentor-photo"><img src="${asset(`mentor-${m.id}.webp`)}" alt="${esc(t(m.name))}" width="1080" height="1440" loading="lazy"></div><div class="mentor-card-copy"><h3>${t(m.name)}</h3><p>${t(m.role)}</p><span class="gateway-link">${u('learn')} <b aria-hidden="true">↗</b></span></div></a>`;
 // The home page is intentionally limited to an opening statement and entry points.
 page('index.html',t(['让内容走得更远','Take Content Further','Donnons de la portée à vos contenus']),`<section class="brand-home"><div class="brand-scene"><img src="${asset('brand-horizon.webp')}" alt="${t(['山海与鲸的抽象品牌雕塑','Abstract sculpture inspired by sea mountains and a whale','Sculpture abstraite inspirée de la mer des montagnes et de la baleine'])}" width="1672" height="941" fetchpriority="high"></div><div class="brand-home-copy"><p class="eyebrow">AUROVOY CULTURE TECHNOLOGY</p><h1>${t(['让内容<br>走得更远','Take content<br>further','Donnons de la portée<br>à vos contenus'])}</h1><p class="brand-home-line">${t(['以文化为起点 与科技共创','Culture and technology in creative dialogue','Culture et technologie en dialogue créatif'])}</p><a class="brand-explore" href="works.html">${u('explore')}<span aria-hidden="true">↗</span></a></div><div class="brand-home-bottom"><span>${t(['连接文化 科技赋能 启程未来','CULTURE CREATIVITY TECHNOLOGY','CULTURE CRÉATIVITÉ TECHNOLOGIE'])}</span><span>AUROVOY</span></div></section><section class="brand-paths" aria-label="${t(['业务方向','What we do','Nos activités'])}">${[['production','production.html','CONTENT'],['training','training.html','LEARNING'],['global','global.html','GLOBAL']].map(([key,href,small])=>`<a href="${href}"><span class="path-label">${small}</span><h2>${u(key)}</h2><span class="path-arrow" aria-hidden="true">↗</span></a>`).join('')}</section>`,'index.html');
 page('works.html',navNames[1],title('AUROVOY / PORTFOLIO',u('workTitle'),u('workIntro'),[[navNames[1]]])+`<section class="section category-section"><div class="category-grid">${categories.map(categoryCard).join('')}</div></section>`+cta(true),'works.html');
 for(const c of categories)page(`works-${c.id}.html`,t(c.name),title('PORTFOLIO',t(c.name),t(c.desc),[[navNames[1],'works.html'],[t(c.name)]],tags(t(c.tags)))+`<section class="section gallery-section">${filmGroups(c.films)}<div class="category-switch"><span>${u('viewAll')}</span>${categories.filter(x=>x!==c).map(x=>`<a href="works-${x.id}.html">${t(x.name)} ↗</a>`).join('')}</div></section>`+cta(true),'works.html');
 for(const f of films){const c=categories.find(x=>x.id===f.category),duration=media[f.id]?.duration;
  const d=duration?`${Math.floor(duration/60)}:${String(Math.floor(duration%60)).padStart(2,'0')}`:'';
  page(`work-${f.id}.html`,t(f.name),`<section class="work-detail section">${crumbs([[navNames[1],'works.html'],[t(c.name),`works-${c.id}.html`],[esc(t(f.name))]])}<div class="work-heading"><div><p class="eyebrow">${t(c.name)}</p><h1>${esc(t(f.name))}</h1></div><a class="text-link" href="works-${c.id}.html">${u('backCat')} ↗</a></div><div class="player-shell ${isPortrait(f.id)?'player-portrait':'player-landscape'}" style="--video-ratio:${layout[f.id].width}/${layout[f.id].height}"><video width="${layout[f.id].width}" height="${layout[f.id].height}" controls playsinline preload="none" poster="${asset(`cover-${f.id}.webp`)}" aria-label="${esc(t(f.name))}"><source src="${asset(`film-${f.id}.mp4`)}" type="video/mp4"><a href="${asset(`film-${f.id}.mp4`)}">${t(['打开视频','Open video','Ouvrir la vidéo'])}</a></video></div><p class="preview-caption">${u('preview')}</p><div class="film-information"><div><h2>${u('category')}</h2><p>${t(c.desc)}</p>${tags(t(c.tags))}</div><dl><div><dt>${u('originalTitle')}</dt><dd>${esc(f.name[0])}</dd></div><div><dt>${u('category')}</dt><dd><a href="works-${c.id}.html">${t(c.name)} ↗</a></dd></div>${d?`<div><dt>${t(['原样片时长','Original duration','Durée du film source'])}</dt><dd>${d}</dd></div>`:''}</dl></div></section><section class="related section"><div class="section-head"><h2>${u('related')}</h2><a class="text-link" href="works-${c.id}.html">${u('viewCat')} ↗</a></div>${filmGroups(c.films.filter(i=>i!==f.id).sort((a,b)=>Number(isPortrait(a))-Number(isPortrait(b))).slice(0,3),3)}</section>`+cta(true),'works.html');
 }
 page('production.html',u('production'),title('01 / DELIVERY',u('production'),u('productionDesc'),[[u('production')]])+`<section class="section"><div class="split-content"><h2>${t(['按内容需求，匹配制作能力。','The right craft for your content.','Les bonnes compétences pour votre contenu.'])}</h2><div><p>${t(['我们可支持从需求判断、创意脚本、视觉资产、动态制作、声音剪辑到版本输出的项目协作，按需匹配全流程制作、剪辑、设计与本地化伙伴。','We coordinate briefs, scripts, visual assets, motion, sound, editing and final versions, matching production, editing, design and localisation specialists to each project.','Nous coordonnons brief, scénario, ressources visuelles, animation, son, montage et versions finales en mobilisant les spécialistes adaptés au projet.'])}</p><p>${t(['面向品牌、企业、内容机构、广告公司与 MCN 提供项目制制作，也可按约定开展白牌承制。内容范围、周期与验收标准在启动前共同确认。','Project-based and agreed white-label production for brands, businesses, studios, agencies and MCNs. Scope, schedule and acceptance criteria are confirmed before work begins.','Production par projet et en marque blanche sur accord pour marques, entreprises, studios, agences et réseaux de créateurs. Périmètre, calendrier et critères de validation sont définis au départ.'])}</p></div></div><div class="capability-links">${categories.map(c=>`<a href="works-${c.id}.html"><span>${t(c.name)}</span><b aria-hidden="true">↗</b></a>`).join('')}</div></section>`+process()+cta(),'works.html');
 const globalSteps=[
  [['目标与现状诊断','评估目标市场、现有内容、预算与商业模式。'],['Diagnose','Review target markets, existing content, budget and business model.'],['Diagnostiquer','Examiner marchés, contenus, budget et modèle économique.']],
  [['规划内容与产品路径','明确内容形态、平台方向、本地化与技术需求。'],['Plan','Define content formats, platforms, localisation and technology needs.'],['Planifier','Définir formats, plateformes, localisation et besoins techniques.']],
  [['形成启动方案','梳理团队、预算与项目排期。'],['Design the launch','Outline the team, budget and project schedule.'],['Préparer le lancement','Définir équipe, budget et calendrier du projet.']],
  [['协同专业伙伴','按需对接制作、本地化、配音、开发及发行推广资源。'],['Connect specialists','Coordinate production, localisation, dubbing, development and distribution resources as needed.'],['Mobiliser les spécialistes','Coordonner production, localisation, doublage, développement et distribution selon les besoins.']]
 ];
 const steps=items=>`<div class="detail-steps">${items.map((s,i)=>`<article><span>0${i+1}</span><div><h3>${t(s)[0]}</h3><p>${t(s)[1]}</p></div></article>`).join('')}</div>`;
 page('global.html',u('global'),title('03 / GLOBAL START',u('globalTitle'),u('globalDesc'),[[navNames[2]]])+`<section class="section"><div class="split-content"><h2>${t(['适合准备迈出下一步的内容团队。','For content teams ready for a next step.','Pour les équipes prêtes à franchir une étape.'])}</h2><p>${t(['面向漫剧公司、短剧团队、IP 与小说公司，以及探索海外业务的小型内容工作室。','For AI drama companies, short-drama teams, IP and publishing businesses, and small studios exploring international opportunities.','Pour les studios de fiction IA, équipes de formats courts, entreprises d’IP et d’édition et studios explorant l’international.'])}</p></div>${steps(globalSteps)}<p class="scope-note">${u('globalScope')}</p></section>`+cta(),'global.html');
 page('training.html',navNames[3],title('02 / LEARN BY MAKING',u('trainingTitle'),u('trainingDesc'),[[navNames[3]]])+`<section class="section course-section"><div class="section-head"><h2>${u('courseLabel')}</h2><a class="text-link" href="partnership.html">${t(['渠道合作','Channel partnerships','Partenariats de formation'])} ↗</a></div><div class="course-grid">${courses.map(courseCard).join('')}</div></section><section class="mentor-teaser section"><p class="eyebrow">${t(['项目实战型导师','PRACTICE-LED INSTRUCTORS','INTERVENANTS DE TERRAIN'])}</p><div class="split-content"><h2>${u('mentorsTitle')}</h2><div><p>${u('mentorsIntro')}</p>${button('mentors.html',u('mentorLink'))}</div></div></section>`+cta(),'training.html');
 for(const c of courses)page(`course-${c.id}.html`,t(c.name),title(`PROGRAMME / ${c.number}`,t(c.name),t(c.desc),[[navNames[3],'training.html'],[t(c.name)]],tags([t(c.time)]))+`<section class="section course-detail"><div class="split-content"><h2>${u('audience')}</h2><p>${t(c.audience)}</p></div><div class="split-content"><h2>${u('outcome')}</h2><ul class="outcome-list">${t(c.results).map(x=>`<li>${x}</li>`).join('')}</ul></div>${c.id==='bootcamp'?`<h2 class="curriculum-title">${u('curriculum')}</h2>${steps(days)}`:`<div class="split-content"><h2>${u('format')}</h2><p>${c.id==='intro'?t(['可用于公开课、直播、社群分享与沙龙，结合案例拆解、制作流程与学习路径。','For public sessions, live streams and community events, combining examples, workflows and learning guidance.','Pour sessions publiques, directs et événements communautaires, avec exemples, workflows et orientation pédagogique.']):t(['先沟通真实业务与团队基础，再确认课程模块、导师与排期；围绕企业内容场景进行实操。','Begin with business needs and team experience, then agree on modules, instructors and schedules, with practice focused on company content needs.','Partir des besoins métier et du niveau des équipes, puis définir modules, intervenants et calendrier autour de cas pratiques adaptés.'])}</p></div>`}<p class="scope-note">${u('trainingNote')}</p>${button('mentors.html',u('mentorLink'))}</section>`+cta(),'training.html');
 const partnerships=[
  [['联合招生','合作方负责招生、转化与客户维护；元启程提供课程、导师、教学交付、作品点评与结营。'],['Joint enrolment','Partners manage recruitment and relationships; AUROVOY provides programmes, instructors, teaching, reviews and completion support.'],['Recrutement conjoint','Le partenaire gère recrutement et relations ; AUROVOY assure programmes, intervenants, enseignement, retours et bilan.']],
  [['导师与课程交付','合作方组织已有学员与基础运营，元启程按场次、天数或班级提供教学支持。'],['Instructors & delivery','Partners organise existing learners and operations; AUROVOY provides teaching by session, day or cohort.'],['Intervenants & enseignement','Le partenaire organise les apprenants ; AUROVOY intervient par session, journée ou promotion.']],
  [['企业与机构定制','合作方连接客户，元启程提供需求诊断、课程设计、导师与企业场景实操。'],['Tailored programmes','Partners connect clients; AUROVOY provides diagnosis, course design, instructors and business-relevant practice.'],['Programmes sur mesure','Le partenaire apporte la relation client ; AUROVOY assure diagnostic, conception, intervenants et pratique métier.']]
 ];
 page('partnership.html',t(['培训渠道合作','Training partnerships','Partenariats de formation']),title('TRAINING / PARTNERSHIPS',t(['从一场公开课，<br>开始一次合作。','Start a partnership<br>with a first session.','Commencer un partenariat<br>par une première session.']),t(['面向培训机构、MCN、企业服务商、园区与协会。','For training providers, MCNs, business service providers, innovation hubs and associations.','Pour organismes de formation, réseaux de créateurs, prestataires, pôles et associations.']),[[navNames[3],'training.html'],[t(['渠道合作','Partnerships','Partenariats'])]])+`<section class="section">${steps(partnerships)}<div class="split-content partnership-flow"><h2>${t(['先跑通一班，再逐步复制。','Learn from a first cohort, then repeat.','Tester une première promotion, puis déployer.'])}</h2><p>${t(['从公开课测试兴趣，进入 7 天训练营，形成结营作品与复盘，再按需求延展进阶训练或企业内训。','Start with an introductory session, move to a seven-day workshop, review completed work, then expand into advanced or corporate training as needed.','Commencer par une session découverte, poursuivre par un atelier de sept jours, analyser les réalisations, puis envisager une formation avancée ou en entreprise.'])}</p></div></section>`+cta(),'training.html');
 page('mentors.html',u('mentorLink'),title('AUROVOY / INSTRUCTORS',u('mentorsTitle'),u('mentorsIntro'),[[navNames[3],'training.html'],[u('mentorLink')]])+`<section class="section"><div class="mentor-grid">${mentors.map(mentorCard).join('')}</div></section>`+cta(),'training.html');
 for(const m of mentors){const profile=mentorDetails[m.id];page(`mentor-${m.id}.html`,t(m.name),`<section class="section mentor-profile">${crumbs([[navNames[3],'training.html'],[u('mentorLink'),'mentors.html'],[t(m.name)]])}<div class="mentor-profile-grid"><div class="mentor-profile-photo"><img src="${asset(`mentor-${m.id}.webp`)}" alt="${esc(t(m.name))}" width="1080" height="1440" fetchpriority="high"></div><div class="mentor-profile-copy"><p class="eyebrow">AUROVOY INSTRUCTOR</p><h1>${t(m.name)}</h1><p class="mentor-role">${t(m.role)}</p>${tags(t(m.tags))}<div class="mentor-biography"><h2>${t(['导师介绍','About the instructor','Présentation'])}</h2>${profile.paragraphs.map(p=>`<p>${t(p)}</p>`).join('')}</div></div></div><div class="mentor-profile-bottom"><section><h2>${t(['专业经历','Professional background','Parcours professionnel'])}</h2><ul>${t(profile.highlights).map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h2>${t(['核心授课方向','Teaching areas','Domaines d’enseignement'])}</h2><ul>${t(profile.teaching).map(x=>`<li>${x}</li>`).join('')}</ul></section></div><a class="text-link" href="mentors.html">${t(['返回导师团队','Back to instructors','Retour aux intervenants'])} ↗</a></section>`+cta(),'training.html');}
 page('about.html',navNames[4],title('AUROVOY / ABOUT',u('aboutTitle'),'',[[navNames[4]]])+`<section class="about section"><div class="about-brand"><img src="${asset('mark.png')}" alt="AUROVOY" width="112" height="118"><p>AUROVOY <span>元启程</span></p><small>CULTURE & TECHNOLOGY</small></div><div><h2>${u('company')}</h2><p>${u('aboutText')}</p><p>${u('aboutTeam')}</p><div class="values">${t(ui.values).map(x=>`<span>${x}</span>`).join('')}</div></div></section><section class="section about-paths">${serviceCards()}</section>`+cta(),'about.html');
 page('contact.html',navNames[5],title('AUROVOY / CONTACT',u('contactCta'),u('contactIntro'),[[navNames[5]]])+`<section class="section contact-page"><div class="email-panel"><span class="eyebrow">${u('emailLabel')}</span><a class="email-address" href="${mail()}">${email}<span aria-hidden="true">↗</span></a>${button(mail(),u('send'))}<p>SHENZHEN, CHINA</p></div><div class="contact-brief"><h2>${u('briefTitle')}</h2><ol>${t(ui.briefItems).map(x=>`<li>${x}</li>`).join('')}</ol><p>${u('company')}</p></div></section>`,'contact.html');
}
console.log(`Generated ${total} pages in Chinese, English and French.`);

