// Editorial profiles adapted from the supplied AUROVOY instructor document.
export const mentorDetails={
 sophie:{
  paragraphs:[
   ['Sophie 拥有英国 MBA 背景与 PMP 项目管理认证，具备多年大型企业项目管理经验。擅长资源整合、跨团队协作与标准化运营，将创意拆解为人员分工、执行路径和交付节点。','Sophie holds a UK MBA and PMP certification, with years of project-management experience in large companies. Her work connects resource planning, cross-team coordination and standardised operations, translating ideas into clear responsibilities, milestones and delivery plans.','Titulaire d’un MBA britannique et de la certification PMP, Sophie possède plusieurs années d’expérience en gestion de projets au sein de grandes entreprises. Elle transforme les idées en responsabilités, étapes et plans de réalisation grâce à la coordination des équipes et des ressources.'],
   ['作为 AI 内容商业项目的制片人与交付负责人，Sophie 的项目覆盖品牌宣传、TVC、定制短片、高端微电影与 AI 漫剧。曾参与多部猫拟人漫剧、红果短剧和海外 TikTok 短剧，担任导演及主要制片人，熟悉策划、剧本开发、制作统筹、本地化与发行链路。','As a producer and delivery lead, Sophie works across brand films, TV commercials, bespoke shorts and AI drama. Her directing and lead-producing experience includes anthropomorphic cat stories, Hongguo short dramas and TikTok dramas for international audiences, from development and production through localisation and distribution.','Productrice et responsable de réalisation, Sophie intervient sur les films de marque, spots publicitaires, courts métrages sur mesure et fictions IA. Son expérience de réalisation et de production comprend des récits de chats anthropomorphes, des fictions Hongguo et des séries TikTok internationales, du développement à la localisation et à la diffusion.'],
   ['课程围绕真实商业项目展开，从需求判断、预算排期、团队组织到验收交付，帮助创作者建立项目管理意识。结合留英期间的创业者生态搭建经验，支持个人 IP 商业模式设计、OPC 项目孵化与内容出海启动。','Her teaching follows real commercial projects, covering briefs, budgets, schedules, team organisation and delivery reviews. Drawing on her experience building an entrepreneur-support community in the UK, she also supports personal-brand business planning, one-person-company project incubation and international content launches.','Son enseignement suit des projets commerciaux concrets, du brief aux budgets, au calendrier, à l’organisation et à la validation. Son expérience d’accompagnement d’entrepreneurs au Royaume-Uni nourrit également ses formations au modèle économique personnel, à l’incubation de projets individuels et au lancement international.']
  ],
  highlights:[['英国 MBA 与 PMP 项目管理认证','大型企业项目管理与跨团队协作','AI 微电影与短剧制片经验','本地化制作与海外发行协同'],['UK MBA and PMP certification','Corporate project management and team coordination','AI short-film and drama production','Localisation and international distribution'],['MBA britannique et certification PMP','Gestion de projets et coordination d’équipes','Production de courts métrages et fictions IA','Localisation et distribution internationale']],
  teaching:[['OPC 项目孵化','AI 微电影高端定制','商业订单交付','内容出海与本地化','个人 IP 商业模式'],['OPC project incubation','Bespoke AI short films','Commercial project delivery','International content and localisation','Personal-brand business models'],['Incubation de projets OPC','Courts métrages IA sur mesure','Réalisation de projets commerciaux','Contenus internationaux et localisation','Modèles économiques de marque personnelle']]
 },
 jiang:{
  paragraphs:[
   ['姜老师是米核 AI 合伙人、深圳模力 OPC 漫剧基地 AIGC 特约讲师，具备 AIGC 课程研发、企业内容项目、AI 视频制作与智能体应用教学经验。关注 AI 工具如何融入可协同、可复用的内容生产系统。','Jiang is a partner at Mihe AI and a guest AIGC instructor at the Shenzhen Moli OPC drama hub. His experience spans curriculum development, corporate content projects, AI video and agent applications, with a focus on collaborative, reusable production systems.','Jiang est associé de Mihe AI et intervenant AIGC invité au pôle de fiction Moli OPC de Shenzhen. Son expérience couvre la conception pédagogique, les projets de contenu d’entreprise, la vidéo IA et les agents, avec une attention particulière aux systèmes de production collaboratifs et réutilisables.'],
   ['在工作流设计中，将大模型、提示词、知识库、自动化节点和内容模板组合起来，串联脚本、图像、视频、音频、剪辑与资料整理。帮助团队把单点工具操作转化为有步骤、有标准的生产流程。','His workflows combine language models, prompts, knowledge bases, automation steps and templates. They connect scripts, images, video, audio, editing and research, helping teams turn individual tool operations into structured production processes.','Ses workflows associent modèles de langage, prompts, bases de connaissances, automatisation et modèles de contenu. Ils relient scénarios, images, vidéo, audio, montage et recherche pour transformer les usages isolés en processus de production structurés.'],
   ['授课以任务拆解和场景实操为核心，可覆盖早安电台、故事与分镜、商业短视频、电商详情页、企业宣传脚本、政策宣讲和 AI 漫剧。适合希望提升内容产能的创作者、企业团队与培训机构。','Teaching centres on task design and practical scenarios, including audio programmes, storyboards, commercial shorts, product pages, corporate scripts, public-information content and AI drama. It is suited to creators, business teams and training organisations developing their production capability.','L’enseignement repose sur la décomposition des tâches et la pratique : programmes audio, storyboards, formats commerciaux, fiches produit, scénarios institutionnels, information publique et fiction IA. Il s’adresse aux créateurs, équipes d’entreprise et organismes de formation.']
  ],
  highlights:[['米核 AI 合伙人','深圳模力 OPC 漫剧基地 AIGC 特约讲师','AIGC 课程研发与企业内容项目经验','脚本 图像 视频 音频的协同工作流'],['Partner at Mihe AI','Guest AIGC instructor at Shenzhen Moli OPC','AIGC curriculum and corporate content experience','Connected script, image, video and audio workflows'],['Associé de Mihe AI','Intervenant AIGC invité chez Moli OPC Shenzhen','Conception pédagogique et contenus d’entreprise','Workflows reliant scénario, image, vidéo et audio']],
  teaching:[['智能体应用','自动化内容生产','AI 视频与漫剧流程','商业短视频与电商内容','企业内容生产模板'],['AI agent applications','Automated content production','AI video and drama workflows','Commercial shorts and commerce content','Corporate production templates'],['Applications d’agents IA','Production automatisée de contenu','Workflows vidéo et fiction IA','Formats commerciaux et e-commerce','Modèles de production d’entreprise']]
 },
 bell:{
  paragraphs:[
   ['贝尔长期从事商业视频、产品视觉、直播内容与政企宣传，具备从创意策划、拍摄执行、团队调度到成片交付的完整项目经验。将传统影像制作方法与 AI 工具结合，关注创意与执行之间的衔接。','Bell works across commercial video, product visuals, live-stream content and institutional communication. His experience covers creative planning, shooting, team coordination and final delivery, combining traditional filmmaking methods with AI tools.','Bell travaille dans la vidéo commerciale, l’image produit, les contenus de direct et la communication institutionnelle. Son expérience va de la conception au tournage, à la coordination des équipes et à la livraison, en associant méthodes audiovisuelles et outils IA.'],
   ['曾参与世界 500 强产品市场广告拍摄的核心执行工作，积累了电商产品视频制作与直播团队带教经验。在政企项目中，担任过龙岗区政府小程序宣发视频项目总导演与全案负责人，统筹创意、视觉呈现及制作交付。','He has held a core execution role on product-marketing advertising shoots for a Fortune Global 500 company and trained live-stream teams. He also served as overall director and project lead for a Longgang District government mini-programme promotional video, coordinating concept, visuals and production.','Il a assuré un rôle clé dans l’exécution de tournages publicitaires produit pour une entreprise du Fortune Global 500 et accompagné des équipes de direct. Il a également dirigé un projet de vidéo promotionnelle pour un mini-programme du gouvernement du district de Longgang, de la conception à la réalisation.'],
   ['在 AI 海外剧与漫剧方向，带领团队完成多部项目制作与发行，探索适合个人和小团队的高效生产方式。课程把项目拆解、制作调度、画面标准与成片验收连接起来，帮助学员理解商业影像交付的实际要求。','In international AI drama and animated storytelling, he has led teams through production and distribution on multiple projects. His teaching links project breakdowns, scheduling, visual standards and final reviews, helping small teams understand the practical demands of commercial delivery.','Dans les fictions IA internationales et les récits animés, il a piloté plusieurs productions et leur diffusion. Ses cours relient découpage du projet, planification, exigences visuelles et validation finale pour transmettre aux petites équipes les réalités de la réalisation commerciale.']
  ],
  highlights:[['模力 OPC 特邀实战导师','世界 500 强产品广告核心执行经验','政企宣传项目总导演经验','海外剧团队制作与发行经验'],['Guest practitioner at Moli OPC','Fortune Global 500 product-advertising experience','Institutional film directing','International drama production and distribution'],['Intervenant praticien invité chez Moli OPC','Expérience publicitaire pour une entreprise du Fortune Global 500','Réalisation de films institutionnels','Production et diffusion de fictions internationales']],
  teaching:[['AI 海外剧制作','品牌广告全流程执行','电商产品短视频','政企宣传交付','直播团队内容训练'],['International AI drama','End-to-end brand advertising','Product short videos','Institutional film delivery','Live-stream team content training'],['Fictions IA internationales','Publicité de marque de bout en bout','Vidéos courtes produit','Réalisation institutionnelle','Formation des équipes de direct']]
 },
 yang:{
  paragraphs:[
   ['子飞是 AI 漫剧 OPC 超级个体实训基地主理人，专注 AI 漫剧实操教学、个人项目孵化与轻资产创业陪跑。服务创作者、自媒体博主、实体创业者及希望转型的政企人员，协助找到适合自身能力的内容商业化路径。','Zifei runs a practical training base for AI drama and one-person companies. His work focuses on hands-on production, individual project incubation and lean entrepreneurship, supporting creators, independent publishers, local business owners and professionals exploring a new direction.','Zifei dirige une base de formation pratique dédiée à la fiction IA et aux entreprises individuelles. Il accompagne la production, l’incubation de projets et l’entrepreneuriat à moyens légers auprès de créateurs, éditeurs indépendants, commerçants et professionnels en reconversion.'],
   ['全流程训练覆盖选题、剧本、角色、场景、分镜、运镜、配音音效、剪辑包装与成片发布。将传统编导的景别、构图、光影、色彩、调度和节奏，转化为学员可以执行的提示词、分镜表与制作标准，让镜头服务叙事。','His training covers concepts, scripts, characters, settings, storyboards, camera movement, sound, editing and release. Framing, composition, lighting, colour and rhythm are translated into practical prompts, shot plans and production standards, with every shot serving the story.','Sa formation couvre sujets, scénarios, personnages, décors, storyboards, mouvements de caméra, son, montage et diffusion. Cadrage, composition, lumière, couleur et rythme deviennent des prompts, plans de tournage et critères concrets au service du récit.'],
   ['曾参与传统影视团队的 AI 转型课程协同交付，并参与福田科教院合作项目，为全国青少年人工智能辅助生成数字艺术创作者大赛提供赛前辅导。课程兼顾导演思维、作品评审、分层学习与个人项目落地。','He has contributed to AI-transition training for traditional film teams and to competition preparation through a Futian education and research institute collaboration for a national youth AI-assisted digital-art competition. His teaching combines directing, portfolio reviews, staged learning and individual project development.','Il a contribué à des formations de transition vers l’IA pour des équipes audiovisuelles et à la préparation d’un concours national jeunesse d’art numérique assisté par IA, dans le cadre d’une collaboration avec l’institut éducatif de Futian. Il associe mise en scène, évaluation des œuvres et progression par étapes.']
  ],
  highlights:[['AI 漫剧 OPC 超级个体实训基地主理人','传统编导视听语言迁移','影视团队 AI 转型课程交付经验','青少年赛事辅导与作品评审'],['AI drama and OPC training-base lead','Cinematic language adapted to AI production','AI-transition training for film teams','Youth competition coaching and portfolio reviews'],['Responsable d’une base de formation fiction IA et OPC','Adaptation du langage cinématographique à l’IA','Formation de transition IA pour équipes audiovisuelles','Accompagnement de concours et évaluation des travaux']],
  teaching:[['AI 漫剧全流程','导演思维与视听语言','分镜 运镜与剪辑节奏','OPC 个人项目孵化','赛事辅导与作品评审'],['Complete AI drama production','Directing and cinematic language','Storyboards, camera movement and editing','OPC project incubation','Competition coaching and portfolio reviews'],['Production complète de fictions IA','Mise en scène et langage audiovisuel','Storyboards, caméra et rythme du montage','Incubation de projets OPC','Préparation aux concours et évaluation']]
 },
 huohuo:{
  paragraphs:[
   ['火火是悦界 AI 运营总监、AI 实体商家获客课程讲师，具备 MCN 操盘、IP 账号运营与 AI 应用实战经验。聚焦实体老板、企业管理者和个人工作室的日常经营场景，将内容生产与客户沟通流程相结合。','Huohuo is operations director at Yuejie AI and an instructor in AI customer acquisition for local businesses. Experience in MCN operations, personal-brand accounts and practical AI applications informs a focus on everyday business content and customer communication.','Huohuo est responsable des opérations chez Yuejie AI et enseigne l’acquisition client par l’IA pour les commerces locaux. Son expérience en réseaux de créateurs, comptes de marque personnelle et applications IA nourrit une approche ancrée dans la communication quotidienne des entreprises.'],
   ['拥有 Datawhale Prompt Engineer 与 Agent Engineer 认证，并完成达摩院智能客服人工智能训练师初级与高级培训课程认证。将提示词、智能体、AI 脚本、图文创作与数字人出镜整合为可执行的业务方案。','Huohuo holds Datawhale Prompt Engineer and Agent Engineer certifications and has completed introductory and advanced AI-trainer certification courses for DAMO Academy intelligent customer service. Teaching combines prompting, agents, scripts, visual content and digital presenters in practical business workflows.','Huohuo possède les certifications Datawhale Prompt Engineer et Agent Engineer et a suivi les cursus certifiants initial et avancé de formateur IA pour le service client intelligent de DAMO Academy. Les cours associent prompts, agents, scénarios, contenus visuels et présentateurs numériques.'],
   ['课程围绕同城内容运营、批量内容生产、数字人 IP、智能体承接与私域沟通展开，帮助商家解决不会写、不会拍、难以持续更新的问题。通过场景拆解与流程练习，建立适合自身门店和服务的内容方法。','Courses cover local content operations, batch production, digital-presenter identities, agent-assisted enquiries and direct customer relationships. Practical exercises help business owners address writing, filming and consistency challenges and build methods suited to their own services.','Les cours abordent communication locale, production en série, identité de présentateur numérique, traitement des demandes par agent et relation directe avec les clients. Les exercices aident les commerçants à surmonter les difficultés d’écriture, de tournage et de régularité avec des méthodes adaptées à leurs services.']
  ],
  highlights:[['悦界 AI 运营总监','MCN 与 IP 账号运营经验','Datawhale Prompt Engineer 与 Agent Engineer 认证','达摩院智能客服 AI 训练师课程认证'],['Operations director at Yuejie AI','MCN and personal-brand account operations','Datawhale Prompt Engineer and Agent Engineer certifications','DAMO Academy AI-trainer course certifications'],['Responsable des opérations chez Yuejie AI','Gestion de réseaux de créateurs et de comptes personnels','Certifications Datawhale Prompt Engineer et Agent Engineer','Certifications de cursus de formateur IA DAMO Academy']],
  teaching:[['AI 实体商家内容与获客','同城短视频运营','数字人 IP','提示词与智能体应用','批量内容生产与客户承接'],['AI content and acquisition for local businesses','Local short-video operations','Digital-presenter identities','Prompting and AI agents','Batch content and customer enquiries'],['Contenus IA et acquisition pour les commerces','Communication vidéo locale','Identités de présentateurs numériques','Prompts et agents IA','Production en série et demandes clients']]
 }
};
