import {adminPage} from './views.mjs';
export function adminNavigation(html,current='works'){
 if(current==='works')html=html.replace('</body>',`<dialog id="zone-dialog" aria-labelledby="zone-title"><form id="zone-form"><h2 id="zone-title">调整作品分区</h2><p id="zone-work"></p><label>目标分区<select id="zone-select" required></select></label><p>保存后同步到中英法网站，作品上架状态保持不变。</p><p id="zone-error" class="error" role="status"></p><div class="publication-actions"><button type="button" id="zone-cancel">取消</button><button class="primary" id="zone-save">保存分区</button></div></form></dialog><dialog id="publication-dialog" aria-labelledby="publication-title"><form id="publication-form"><p class="eyebrow">PUBLICATION</p><h2 id="publication-title">选择上架专区</h2><p id="publication-work"></p><label id="publication-zone-label">展示专区<select id="publication-zone" required></select></label><p id="publication-note" class="admin-tip"></p><p id="publication-error" class="error" role="status"></p><div class="publication-actions"><button type="button" id="publication-cancel">取消</button><button class="primary" id="publication-submit">确认并同步</button></div></form></dialog></body>`);
 return html.replace('</header>' ,`</header><nav class="admin-sections" aria-label="管理内容">${[['works','作品管理','/admin'],['courses','培训课程','/admin/training'],['mentors','导师团队','/admin/mentors']].map(([key,name,url])=>`<a href="${url}"${key===current?' aria-current="page"':''}>${name}</a>`).join('')}</nav>`);
}
export function contentAdminPage(kind){
 const mentor=kind==='mentors',name=mentor?'导师团队':'培训课程';
 const main=`<main class="admin-main" data-content-kind="${kind}"><div class="admin-heading"><div><p class="eyebrow">${mentor?'OUR INSTRUCTORS':'LEARNING STUDIO'}</p><h1>${name}</h1><p>${mentor?'更新导师资料与形象照 让团队介绍保持最新':'维护课程介绍与详细大纲 保留现有案例和页面设计'}</p></div>${mentor?'<button class="primary" id="new-content">＋ 新增导师</button>':''}</div><p id="content-status" role="status">正在读取资料</p><div class="library"><div class="library-tools"><label>查找${mentor?'导师':'课程'}<input id="content-search" type="search" placeholder="输入名称"></label><label>显示状态<select id="content-filter"><option value="all">全部</option><option value="published">对外展示</option><option value="draft">暂不展示</option></select></label></div><div class="table-scroll"><table><thead><tr><th>${mentor?'导师':'课程'}</th><th>${mentor?'职务与方向':'时长'}</th><th>状态</th><th>排序</th><th>管理</th></tr></thead><tbody id="content-list"></tbody></table></div></div><p class="admin-tip">保存后同步到中英法网站　暂不展示的资料仍可在后台修改${mentor?'　移除导师后原详情页也会停止展示':''}</p></main>`;
 const dialog=`<dialog id="content-editor" aria-labelledby="content-editor-title"><div class="editor-top"><div><p class="eyebrow">${mentor?'INSTRUCTOR PROFILE':'COURSE EDITOR'}</p><h2 id="content-editor-title">${mentor?'编辑导师':'编辑课程'}</h2></div><button type="button" id="content-close" aria-label="关闭">×</button></div><form id="content-form"><div class="editor-grid"><aside class="media-column"><div class="poster-preview ${mentor?'mentor-preview':''}"><img id="content-photo" alt="${mentor?'导师形象照':'课程图片'}" hidden><span id="content-photo-empty">${mentor?'导师形象照':'课程封面'}</span></div><label>更换${mentor?'导师照片':'课程图片'}<input id="content-photo-file" type="file" accept="image/jpeg,image/png,image/webp"></label><small>JPG PNG WebP　最大 10 MB${mentor?'　建议使用竖版专业形象照':''}</small><p id="content-upload-status" role="status"></p><label>显示状态<select id="content-state"><option value="draft">暂不展示</option><option value="published">对外展示</option></select></label><label>排列顺序<input id="content-order" type="number" min="-999999" max="999999" step="1" required></label><small>数字越小越靠前</small></aside><div class="fields-column"><label class="language-editor">正在编辑的语言<select id="content-language"><option value="0">中文</option><option value="1">English</option><option value="2">Français</option></select></label><small>切换语言会保留编辑。修改中文后保存，将自动更新对应译文。</small><label class="auto-translate"><input type="checkbox" id="content-auto-translate" checked> 保存中文时自动生成英法版本</label><div id="content-fields"></div>${mentor?'':`<section class="module-editor"><div class="module-heading"><h3>详细课程大纲</h3><button type="button" id="add-module">＋ 添加模块</button></div><p class="admin-tip">每个模块可分别填写学习内容 课堂练习和阶段成果</p><div id="module-fields"></div></section>`}</div></div><div class="editor-bottom"><p id="content-save-status" role="status"></p><button class="primary" id="content-save" type="submit">保存并同步</button></div></form></dialog>`;
 let html=adminPage().replace('<title>作品管理 | AUROVOY 元启程</title>',`<title>${name} | AUROVOY 内容管理</title>`).replace('<span>作品管理</span>','<span>内容管理</span>').replace(/<main class="admin-main">[\s\S]*?<\/main>/,main).replace(/<dialog id="editor"[\s\S]*?<\/dialog>/,dialog).replace('/admin.js','/content-admin.js').replace('</head>','<link rel="stylesheet" href="/content-admin.css"></head>');
 return adminNavigation(html,kind);
}
