(()=>{'use strict';
const $=s=>document.querySelector(s),form=$('#work-form'),dialog=$('#editor');let works=[],cats=[],current=null,uploading=false,controller=null,uploadId=null,dirty=false;
const pendingStatus=new Set();let publicationWork=null;const zoneName=w=>cats.find(c=>c.id===w.category)?.name||w.category;
const statusLabel=w=>w.status==='published'?'已上架':w.hasBeenPublished?'已下架':'草稿';
const escape=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function api(path,options={}){const r=await fetch('/api/admin/'+path,{...options,headers:{'Content-Type':'application/json','X-Aurovoy-Admin':'1',...options.headers}});let data;try{data=await r.json();}catch{throw new Error('服务器暂时无法响应 请稍后重试');}if(!r.ok)throw new Error(data.error||'操作未成功');return data;}
function message(el,text,error=false){el.textContent=text;el.classList.toggle('error',error);}
function render(){const q=$('#search').value.trim().toLowerCase(),state=$('#status-filter').value,zone=$('#zone-filter').value;const rows=works.filter(w=>(zone==='all'||w.category===zone)&&(state==='all'||w.status===state)&&w.titles.join(' ').toLowerCase().includes(q));$('#library-count').textContent=`${rows.length} 个作品`;$('#work-list').innerHTML=rows.map(w=>`<tr><td><div class="work-cell">${w.poster?`<img src="${escape(w.poster)}" alt="" loading="lazy">`:''}<strong>${escape(w.titles[0])}</strong></div></td><td>${escape(cats.find(c=>c.id===w.category)?.name)}</td><td><span class="badge ${w.status}">${statusLabel(w)}</span></td><td>${w.order}</td><td><div class="work-actions"><button data-edit="${w.id}" ${pendingStatus.has(w.id)?'disabled':''}>编辑</button><button data-status="${w.id}" class="status-action ${w.status==='published'?'take-down':'put-up'}" ${pendingStatus.has(w.id)?'disabled':''}>${pendingStatus.has(w.id)?'同步中':w.status==='published'?'下架':'上架'}</button></div></td></tr>`).join('')||'<tr><td colspan="5">没有找到作品</td></tr>';}
async function load(){const data=await api('works');works=data.works;cats=data.categories;form.elements.category.innerHTML=cats.map(c=>`<option value="${c.id}">${escape(c.name)}</option>`).join('');$('#zone-filter').innerHTML='<option value="all">全部专区</option>'+form.elements.category.innerHTML;$('#publication-zone').innerHTML=form.elements.category.innerHTML;render();message($('#page-status'),'作品已同步');}
function preview(){const img=$('#poster-preview'),v=$('#video-preview');img.hidden=!current.poster;$('#poster-empty').hidden=!!current.poster;if(current.poster)img.src=current.poster;v.hidden=!current.video;if(current.video){v.src=current.video;v.poster=current.poster;}else v.removeAttribute('src');}
function open(w){current=structuredClone(w);['zh','en','fr'].forEach((l,i)=>{form.elements[`title-${l}`].value=w.titles[i];form.elements[`desc-${l}`].value=w.descriptions[i];});['category','orientation','status','order'].forEach(k=>form.elements[k].value=w[k]);$('#poster-file').value='';$('#video-file').value='';message($('#save-status'),'');message($('#upload-status'),'');$('#upload-progress').hidden=true;preview();dirty=false;dialog.showModal();}
function close(){if(uploading){message($('#save-status'),'请先等待上传完成或取消上传');return;}if(dirty&&!confirm('当前文字修改尚未保存 确定关闭吗'))return;$('#video-preview').pause();dialog.close();}
$('#close-editor').addEventListener('click',close);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});form.addEventListener('input',()=>dirty=true);
$('#new-work').addEventListener('click',async e=>{e.target.disabled=true;try{const w=await api('works',{method:'POST',body:'{}'});works.unshift(w);render();open(w);}catch(err){message($('#page-status'),err.message,true);}finally{e.target.disabled=false;}});
function choosePublication(id){
 const w=works.find(w=>w.id===id);if(!w||pendingStatus.has(id))return;publicationWork=w;
 const up=w.status!=='published';$('#publication-title').textContent=up?'选择上架专区':'从当前专区下架';$('#publication-work').textContent=w.titles[0];$('#publication-zone').value=w.category;$('#publication-zone').disabled=!up;
 $('#publication-note').textContent=up?'作品将展示在所选专区和作品总览中 每部作品归属一个专区':`将从「${zoneName(w)}」和作品总览移除 文件与资料保留`;
 $('#publication-submit').textContent=up?'上架并同步':'下架并同步';message($('#publication-error'),'');$('#publication-dialog').showModal();
}
$('#publication-cancel').addEventListener('click',()=>{if(!pendingStatus.has(publicationWork?.id))$('#publication-dialog').close();});
$('#publication-dialog').addEventListener('cancel',e=>{if(pendingStatus.has(publicationWork?.id))e.preventDefault();});
$('#publication-form').addEventListener('submit',async e=>{
 e.preventDefault();const w=publicationWork;if(!w||pendingStatus.has(w.id))return;const status=w.status==='published'?'draft':'published',category=status==='published'?$('#publication-zone').value:w.category;
 pendingStatus.add(w.id);render();$('#publication-submit').disabled=true;$('#publication-cancel').disabled=true;$('#publication-zone').disabled=true;
 try{const updated=await api(`works/${w.id}/status`,{method:'PATCH',body:JSON.stringify({status,category,updatedAt:w.updatedAt})});works=works.map(item=>item.id===w.id?updated:item);message($('#page-status'),status==='published'?`「${updated.titles[0]}」已上架至「${zoneName(updated)}」专区`:`「${updated.titles[0]}」已从「${zoneName(updated)}」专区下架 文件和资料已保留`);$('#publication-dialog').close();}
 catch(err){message($('#publication-error'),err.message,true);}finally{pendingStatus.delete(w.id);render();$('#publication-submit').disabled=false;$('#publication-cancel').disabled=false;$('#publication-zone').disabled=status==='draft';}
});
$('#work-list').addEventListener('click',e=>{const action=e.target.closest('[data-status]');if(action){choosePublication(action.dataset.status);return;}const b=e.target.closest('[data-edit]');if(b)open(works.find(w=>w.id===b.dataset.edit));});$('#search').addEventListener('input',render);$('#status-filter').addEventListener('change',render);$('#zone-filter').addEventListener('change',render);
form.addEventListener('submit',async e=>{e.preventDefault();if(uploading)return;const b=$('#save-work');b.disabled=true;try{const data={...current,titles:['zh','en','fr'].map(l=>form.elements[`title-${l}`].value),descriptions:['zh','en','fr'].map(l=>form.elements[`desc-${l}`].value),category:form.elements.category.value,orientation:form.elements.orientation.value,status:form.elements.status.value,order:Number(form.elements.order.value)};current=await api(`works/${current.id}`,{method:'PUT',body:JSON.stringify(data)});works=works.map(w=>w.id===current.id?current:w).sort((a,b)=>a.order-b.order);render();dirty=false;message($('#save-status'),current.status==='published'?`已上架至「${zoneName(current)}」专区 官网已同步`:`已保存 暂不上架 预设专区为「${zoneName(current)}」`);}catch(err){message($('#save-status'),err.message,true);}finally{b.disabled=false;}});
function lock(on){uploading=on;$('#save-work').disabled=on;$('#poster-file').disabled=on;$('#video-file').disabled=on;$('#cancel-upload').hidden=!on;}
async function upload(file,kind){if(!file)return;if(current.status!=='draft'){message($('#upload-status'),'请先将发布状态改为草稿并保存 再替换文件',true);return;}if(file.size>(kind==='video'?500:10)*1024*1024){message($('#upload-status'),'文件过大 视频最大 500 MB 封面最大 10 MB',true);return;}
 lock(true);controller=new AbortController();const progress=$('#upload-progress');progress.hidden=false;progress.value=0;message($('#upload-status'),'正在准备上传');
 try{const start=await api('uploads',{method:'POST',body:JSON.stringify({workId:current.id,kind,size:file.size,type:file.type||'video/mp4'}),signal:controller.signal});uploadId=start.id;const chunk=kind==='video'?start.chunkSize:file.size;
  for(let offset=0,part=1;offset<file.size;offset+=chunk,part++){let success=false;for(let attempt=0;attempt<3&&!success;attempt++){try{await api(`uploads/${uploadId}/${part}`,{method:'PUT',body:file.slice(offset,offset+chunk),headers:{'Content-Type':'application/octet-stream'},signal:controller.signal});success=true;}catch(err){if(controller.signal.aborted||attempt===2)throw err;message($('#upload-status'),'网络波动 正在重试当前分段');}}progress.value=Math.min(100,Math.round((offset+chunk)/file.size*100));message($('#upload-status'),`已上传 ${progress.value}%`);}
  const updated=await api(`uploads/${uploadId}/complete`,{method:'POST',body:'{}',signal:controller.signal});current=updated;works=works.map(w=>w.id===current.id?current:w);render();preview();message($('#upload-status'),'文件已保存 请确认画面方向并保存发布设置');uploadId=null;
 }catch(err){message($('#upload-status'),controller.signal.aborted?'上传已取消':`${err.message} 可重新选择文件上传`,true);if(uploadId)await api(`uploads/${uploadId}`,{method:'DELETE'}).catch(()=>{});}finally{uploadId=null;controller=null;lock(false);}}
$('#poster-file').addEventListener('change',e=>upload(e.target.files[0],'poster'));$('#video-file').addEventListener('change',e=>upload(e.target.files[0],'video'));$('#cancel-upload').addEventListener('click',()=>controller?.abort());window.addEventListener('beforeunload',e=>{if(uploading||dirty){e.preventDefault();e.returnValue='';}});
load().catch(err=>message($('#page-status'),err.message,true));
})();
