(()=>{'use strict';const $=s=>document.querySelector(s),kind=$('[data-content-kind]').dataset.contentKind,isMentor=kind==='mentors',dialog=$('#content-editor'),form=$('#content-form');let items=[],draft=null,lang=0,dirty=false,busy=false;const pending=new Set();
const fields=isMentor?[['name','导师姓名',180,1],['role','职务与专业方向',300,2],['bio','简要介绍',1500,3],['biography','详细导师介绍',12000,8],['tags','专业标签 每行一项',1000,3],['highlights','专业经历 每行一项',4000,5],['teaching','授课方向 每行一项',4000,5]]:[['name','课程名称',180,1],['time','课程时长',150,1],['desc','课程简介',3000,4],['audience','适合人群',3000,3],['results','学习成果 每行一项',5000,5]];
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');const say=(s,text,error=false)=>{const e=$(s);e.textContent=text;e.classList.toggle('error',error);};
async function api(suffix='',options={}){const r=await fetch(`/api/admin/content/${kind}${suffix}`,{...options,headers:{'Content-Type':'application/json','X-Aurovoy-Admin':'1',...options.headers}});let value;try{value=await r.json();}catch{throw Error('服务器暂时无法响应 请稍后重试');}if(!r.ok)throw Error(value.error||'操作未完成');return value;}
function renderList(){const q=$('#content-search').value.trim().toLowerCase(),filter=$('#content-filter').value;$('#content-list').innerHTML=items.filter(x=>(filter==='all'||x.status===filter)&&x.name.join(' ').toLowerCase().includes(q)).map(x=>`<tr><td><div class="work-cell">${x.photo?`<img src="${esc(x.photo)}" alt="" loading="lazy">`:''}<strong>${esc(x.name[0])}</strong></div></td><td>${esc((isMentor?x.role:x.time)[0])}</td><td><span class="badge ${x.status}">${x.status==='published'?'对外展示':'暂不展示'}</span></td><td>${x.order}</td><td><div class="content-actions"><button data-edit="${x.id}" ${pending.has(x.id)?'disabled':''}>编辑</button><button data-state="${x.id}" ${pending.has(x.id)?'disabled':''}>${x.status==='published'?'隐藏':'显示'}</button>${isMentor?`<button class="remove-content" data-remove="${x.id}" ${pending.has(x.id)?'disabled':''}>移除</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="5">暂未找到资料</td></tr>';}
async function load(){items=(await api()).items;renderList();say('#content-status','资料已同步');}
function field(key,label,max,rows,value){return `<label>${label}${rows===1?`<input data-field="${key}" maxlength="${max}" value="${esc(value)}">`:`<textarea data-field="${key}" maxlength="${max}" rows="${rows}">${esc(value)}</textarea>`}</label>`;}
function renderFields(){
 $('#content-fields').innerHTML=fields.map(([k,label,max,rows])=>field(k,label,max,rows,draft[k][lang])).join('');
 if(!isMentor)$('#module-fields').innerHTML=draft.modules.map((m,i)=>`<article class="module-card" data-module="${i}"><header><strong>模块 ${i+1}</strong><div class="module-actions"><button type="button" data-module-up="${i}" ${i===0?'disabled':''}>上移</button><button type="button" data-module-down="${i}" ${i===draft.modules.length-1?'disabled':''}>下移</button><button type="button" data-module-remove="${i}">移除</button></div></header>${[['title','模块名称',200,1],['lesson','学习内容',4000,3],['exercise','课堂练习',4000,3],['outcome','阶段成果',4000,2]].map(([k,label,max,rows])=>field(k,label,max,rows,m[k][lang])).join('')}</article>`).join('');
}
function collect(){for(const [k] of fields)draft[k][lang]=$(`#content-fields [data-field="${k}"]`).value;if(!isMentor)document.querySelectorAll('[data-module]').forEach(card=>{const m=draft.modules[Number(card.dataset.module)];card.querySelectorAll('[data-field]').forEach(input=>m[input.dataset.field][lang]=input.value);});draft.status=$('#content-state').value;draft.order=Number($('#content-order').value);}
function photo(){const image=$('#content-photo');image.hidden=!draft.photo;$('#content-photo-empty').hidden=!!draft.photo;if(draft.photo)image.src=draft.photo;}
function open(item){draft=structuredClone(item);lang=0;dirty=false;$('#content-language').value='0';$('#content-state').value=draft.status;$('#content-order').value=draft.order;$('#content-photo-file').value='';say('#content-save-status','');say('#content-upload-status','');photo();renderFields();dialog.showModal();}
function close(){if(busy){say('#content-save-status','请等待保存或上传完成');return;}if(dirty&&!confirm('有尚未保存的文字修改 确定关闭吗'))return;dialog.close();}
$('#content-close').addEventListener('click',close);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});form.addEventListener('input',()=>dirty=true);$('#content-language').addEventListener('change',e=>{collect();lang=Number(e.target.value);renderFields();});
function update(item){items=items.map(x=>x.id===item.id?item:x).sort((a,b)=>a.order-b.order);renderList();}
const disabledBefore=new Map();
function lock(value){busy=value;if(value){form.querySelectorAll('input,select,textarea,button').forEach(el=>{disabledBefore.set(el,el.disabled);el.disabled=true;});}else{for(const [el,disabled] of disabledBefore)el.disabled=disabled;disabledBefore.clear();}}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;collect();lock(true);try{const saved=await api('/'+draft.id,{method:'PUT',body:JSON.stringify(draft)});draft=saved;update(saved);dirty=false;say('#content-save-status',saved.status==='published'?'已保存 对外网站已同步':'已保存 暂不对外展示');}catch(err){say('#content-save-status',err.message,true);}finally{lock(false);}});
$('#content-photo-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024){say('#content-upload-status','图片最大 10 MB',true);return;}collect();lock(true);say('#content-upload-status','正在上传图片');try{const saved=await api('/'+draft.id+'/photo',{method:'PUT',headers:{'Content-Type':file.type,'X-Content-Revision':draft.revision},body:file});draft.photo=saved.photo;draft.revision=saved.revision;draft.updatedAt=saved.updatedAt;update(saved);photo();say('#content-upload-status','照片已保存 文字修改请点击保存并同步');}catch(err){say('#content-upload-status',err.message,true);}finally{lock(false);}});
$('#content-list').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.edit||b.dataset.state||b.dataset.remove,item=items.find(x=>x.id===id);if(!item||pending.has(id))return;if(b.dataset.edit){open(item);return;}const remove=!!b.dataset.remove;if(remove&&!confirm(`确定移除导师「${item.name[0]}」吗\n官网和后台列表将不再展示此导师 仅暂时不展示请使用隐藏`))return;pending.add(id);renderList();try{const saved=await api('/'+id+(remove?'':'/status'),{method:remove?'DELETE':'PATCH',body:JSON.stringify({revision:item.revision,status:item.status==='published'?'draft':'published'})});if(remove)items=items.filter(x=>x.id!==id);else update(saved);say('#content-status',remove?'导师已移除 官网已同步':saved.status==='published'?'已恢复展示 官网已同步':'已隐藏 官网已同步');}catch(err){say('#content-status',err.message,true);}finally{pending.delete(id);renderList();}});
$('#new-content')?.addEventListener('click',async e=>{e.target.disabled=true;try{const item=await api('',{method:'POST',body:'{}'});items.unshift(item);renderList();open(item);}catch(err){say('#content-status',err.message,true);}finally{e.target.disabled=false;}});
$('#content-search').addEventListener('input',renderList);$('#content-filter').addEventListener('change',renderList);
$('#add-module')?.addEventListener('click',()=>{collect();if(draft.modules.length>=40){say('#content-save-status','最多 40 个模块');return;}draft.modules.push({title:['','',''],lesson:['','',''],exercise:['','',''],outcome:['','','']});dirty=true;renderFields();});
$('#module-fields')?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;collect();const k=['moduleUp','moduleDown','moduleRemove'].find(k=>b.dataset[k]!==undefined);if(!k)return;const i=Number(b.dataset[k]);if(k==='moduleRemove'){if(!confirm('确定移除这个课程模块吗'))return;draft.modules.splice(i,1);}else{const to=k==='moduleUp'?i-1:i+1;if(to<0||to>=draft.modules.length)return;[draft.modules[i],draft.modules[to]]=[draft.modules[to],draft.modules[i]];}dirty=true;renderFields();});
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});load().catch(err=>say('#content-status',err.message,true));
})();
